// Official Company Branding - Authentic designs for each shipping/logistics company
// All colors, fonts, and design elements match the official company identity

export interface CompanyBranding {
  id: string;
  name: string;
  nameAr: string;
  country: string;
  logo: string;
  logoLight?: string;
  favicon?: string;
  colors: {
    primary: string;
    primaryDark?: string;
    primaryLight?: string;
    secondary: string;
    secondaryDark?: string;
    secondaryLight?: string;
    accent: string;
    accentDark?: string;
    background: string;
    surface: string;
    text: string;
    textLight: string;
    textOnPrimary: string;
    border: string;
    success: string;
    warning: string;
    error: string;
  };
  gradients: {
    primary: string;
    secondary: string;
    accent: string;
  };
  fonts: {
    primary: string;
    primaryAr?: string;
    heading?: string;
    headingAr?: string;
  };
  buttonStyles: {
    primary: string;
    secondary: string;
    outline: string;
    link: string;
  };
  borderRadius: {
    sm: string;
    md: string;
    lg: string;
    xl: string;
  };
  shadows: {
    sm: string;
    md: string;
    lg: string;
    xl: string;
  };
  heroImage: string;
  ogImage: string;
  description: string;
  website?: string;
  officialColors?: string[];
}

export const COMPANY_BRANDINGS: Record<string, CompanyBranding> = {
  // === INTERNATIONAL EXPRESS ===
  aramex: {
    id: 'aramex',
    name: 'Aramex',
    nameAr: 'أرامكس',
    country: 'UAE',
    logo: '/og-aramex.jpg',
    colors: {
      primary: '#E30613',
      primaryDark: '#B8000F',
      primaryLight: '#FF2A3A',
      secondary: '#FFFFFF',
      accent: '#F5F5F5',
      background: '#FFFFFF',
      surface: '#FFFFFF',
      text: '#1A1A1A',
      textLight: '#666666',
      textOnPrimary: '#FFFFFF',
      border: '#E0E0E0',
      success: '#007A3D',
      warning: '#FFA500',
      error: '#DC2626',
    },
    gradients: {
      primary: 'linear-gradient(135deg, #E30613 0%, #FF2A3A 100%)',
      secondary: 'linear-gradient(135deg, #FFFFFF 0%, #F5F5F5 100%)',
      accent: 'linear-gradient(90deg, #E30613 0%, #B8000F 100%)',
    },
    fonts: {
      primary: 'Arial, sans-serif',
      primaryAr: 'Noto Kufi Arabic, Arial, sans-serif',
    },
    buttonStyles: {
      primary: 'bg-gradient-to-r from-red-600 to-red-700 hover:from-red-700 hover:to-red-800 text-white font-bold py-3 px-6 rounded-lg shadow-lg transition-all duration-300 transform hover:scale-105',
      secondary: 'bg-white border-2 border-red-600 text-red-600 hover:bg-red-50 font-semibold py-3 px-6 rounded-lg',
      outline: 'bg-transparent border-2 border-gray-300 text-gray-700 hover:border-red-600 hover:text-red-600 font-semibold py-3 px-6 rounded-lg',
      link: 'text-red-600 hover:text-red-700 font-semibold underline-offset-4 hover:underline',
    },
    borderRadius: {
      sm: '4px',
      md: '8px',
      lg: '12px',
      xl: '16px',
    },
    shadows: {
      sm: '0 1px 2px rgba(227, 6, 19, 0.1)',
      md: '0 2px 4px rgba(227, 6, 19, 0.15)',
      lg: '0 4px 8px rgba(227, 6, 19, 0.2)',
      xl: '0 8px 16px rgba(227, 6, 19, 0.25)',
    },
    heroImage: '/og-aramex.jpg',
    ogImage: '/og-aramex.jpg',
    description: 'شركة أرامكس - الرائد في حلول الشحن واللوجستيات في المنطقة',
    website: 'https://www.aramex.com',
    officialColors: ['#E30613', '#FFFFFF', '#F5F5F5'],
  },

  dhl: {
    id: 'dhl',
    name: 'DHL Express',
    nameAr: 'دي إتش إل إكسبريس',
    country: 'International',
    logo: 'https://www.dhl.com/content/dam/dhl/global/core/images/logos/dhl-logo.svg',
    colors: {
      primary: '#FFCC00',
      primaryDark: '#D4A500',
      primaryLight: '#FFD633',
      secondary: '#D40511',
      secondaryDark: '#A8000C',
      secondaryLight: '#E01C2A',
      accent: '#000000',
      background: '#FFFFFF',
      surface: '#F5F5F5',
      text: '#1A1A1A',
      textLight: '#666666',
      textOnPrimary: '#000000',
      border: '#E0E0E0',
      success: '#007A3D',
      warning: '#FFA500',
      error: '#DC2626',
    },
    gradients: {
      primary: 'linear-gradient(135deg, #FFCC00 0%, #FFD633 100%)',
      secondary: 'linear-gradient(135deg, #D40511 0%, #E01C2A 100%)',
      accent: 'linear-gradient(90deg, #FFCC00 0%, #D40511 100%)',
    },
    fonts: {
      primary: 'DHL Global, Arial, sans-serif',
      primaryAr: 'Noto Kufi Arabic, Arial, sans-serif',
    },
    buttonStyles: {
      primary: 'bg-gradient-to-r from-yellow-400 to-yellow-500 hover:from-yellow-500 hover:to-yellow-600 text-black font-bold py-3 px-6 rounded-lg shadow-lg transition-all duration-300 transform hover:scale-105',
      secondary: 'bg-red-600 hover:bg-red-700 text-white font-bold py-3 px-6 rounded-lg',
      outline: 'bg-transparent border-2 border-yellow-500 text-yellow-600 hover:bg-yellow-50 font-semibold py-3 px-6 rounded-lg',
      link: 'text-yellow-600 hover:text-yellow-700 font-semibold underline-offset-4 hover:underline',
    },
    borderRadius: {
      sm: '4px',
      md: '8px',
      lg: '12px',
      xl: '16px',
    },
    shadows: {
      sm: '0 1px 2px rgba(255, 204, 0, 0.2)',
      md: '0 2px 4px rgba(255, 204, 0, 0.25)',
      lg: '0 4px 8px rgba(255, 204, 0, 0.3)',
      xl: '0 8px 16px rgba(255, 204, 0, 0.35)',
    },
    heroImage: '/og-dhl.jpg',
    ogImage: '/og-dhl.jpg',
    description: 'دي إتش إل إكسبريس - أسرع خدمة توصيل دولي في العالم',
    website: 'https://www.dhl.com',
    officialColors: ['#FFCC00', '#D40511', '#000000'],
  },

  fedex: {
    id: 'fedex',
    name: 'FedEx',
    nameAr: 'فيديكس',
    country: 'International',
    logo: 'https://www.fedex.com/content/dam/fedex-com/logos/logo.png',
    colors: {
      primary: '#4D148C',
      primaryDark: '#3A0F6A',
      primaryLight: '#6330A8',
      secondary: '#FF6600',
      secondaryDark: '#CC5200',
      secondaryLight: '#FF8533',
      accent: '#000000',
      background: '#FFFFFF',
      surface: '#F8F8F8',
      text: '#1A1A1A',
      textLight: '#666666',
      textOnPrimary: '#FFFFFF',
      border: '#E0E0E0',
      success: '#007A3D',
      warning: '#FFA500',
      error: '#DC2626',
    },
    gradients: {
      primary: 'linear-gradient(135deg, #4D148C 0%, #6330A8 100%)',
      secondary: 'linear-gradient(135deg, #FF6600 0%, #FF8533 100%)',
      accent: 'linear-gradient(90deg, #4D148C 0%, #FF6600 100%)',
    },
    fonts: {
      primary: 'FedEx Sans, Arial, sans-serif',
      primaryAr: 'Noto Kufi Arabic, Arial, sans-serif',
    },
    buttonStyles: {
      primary: 'bg-gradient-to-r from-purple-700 to-purple-800 hover:from-purple-800 hover:to-purple-900 text-white font-bold py-3 px-6 rounded-lg shadow-lg transition-all duration-300 transform hover:scale-105',
      secondary: 'bg-orange-600 hover:bg-orange-700 text-white font-bold py-3 px-6 rounded-lg',
      outline: 'bg-transparent border-2 border-purple-700 text-purple-700 hover:bg-purple-50 font-semibold py-3 px-6 rounded-lg',
      link: 'text-purple-700 hover:text-purple-800 font-semibold underline-offset-4 hover:underline',
    },
    borderRadius: {
      sm: '4px',
      md: '8px',
      lg: '12px',
      xl: '16px',
    },
    shadows: {
      sm: '0 1px 2px rgba(77, 20, 140, 0.15)',
      md: '0 2px 4px rgba(77, 20, 140, 0.2)',
      lg: '0 4px 8px rgba(77, 20, 140, 0.25)',
      xl: '0 8px 16px rgba(77, 20, 140, 0.3)',
    },
    heroImage: '/og-fedex.jpg',
    ogImage: '/og-fedex.jpg',
    description: 'فيديكس - حلول شحن دولي موثوقة ومتقدمة',
    website: 'https://www.fedex.com',
    officialColors: ['#4D148C', '#FF6600', '#000000'],
  },

  ups: {
    id: 'ups',
    name: 'UPS',
    nameAr: 'يو بي إس',
    country: 'International',
    logo: 'https://www.ups.com/assets/resources/webcontent/images/ups-logo.svg',
    colors: {
      primary: '#351C15',
      primaryDark: '#2A1612',
      primaryLight: '#4A2A20',
      secondary: '#FFB500',
      secondaryDark: '#CC9200',
      secondaryLight: '#FFCC33',
      accent: '#000000',
      background: '#FFFFFF',
      surface: '#F8F6F3',
      text: '#1A1A1A',
      textLight: '#666666',
      textOnPrimary: '#FFFFFF',
      border: '#E0DDD8',
      success: '#007A3D',
      warning: '#FFA500',
      error: '#DC2626',
    },
    gradients: {
      primary: 'linear-gradient(135deg, #351C15 0%, #4A2A20 100%)',
      secondary: 'linear-gradient(135deg, #FFB500 0%, #FFCC33 100%)',
      accent: 'linear-gradient(90deg, #351C15 0%, #FFB500 100%)',
    },
    fonts: {
      primary: 'UPS Sans, Arial, sans-serif',
      primaryAr: 'Noto Kufi Arabic, Arial, sans-serif',
    },
    buttonStyles: {
      primary: 'bg-gradient-to-r from-amber-900 to-amber-800 hover:from-amber-950 hover:to-amber-900 text-white font-bold py-3 px-6 rounded-lg shadow-lg transition-all duration-300 transform hover:scale-105',
      secondary: 'bg-amber-500 hover:bg-amber-600 text-black font-bold py-3 px-6 rounded-lg',
      outline: 'bg-transparent border-2 border-amber-900 text-amber-900 hover:bg-amber-50 font-semibold py-3 px-6 rounded-lg',
      link: 'text-amber-800 hover:text-amber-900 font-semibold underline-offset-4 hover:underline',
    },
    borderRadius: {
      sm: '4px',
      md: '8px',
      lg: '12px',
      xl: '16px',
    },
    shadows: {
      sm: '0 1px 2px rgba(53, 28, 21, 0.15)',
      md: '0 2px 4px rgba(53, 28, 21, 0.2)',
      lg: '0 4px 8px rgba(53, 28, 21, 0.25)',
      xl: '0 8px 16px rgba(53, 28, 21, 0.3)',
    },
    heroImage: '/og-ups.jpg',
    ogImage: '/og-ups.jpg',
    description: 'يو بي إس - حلول شحن موثوقة حول العالم',
    website: 'https://www.ups.com',
    officialColors: ['#351C15', '#FFB500', '#000000'],
  },

  // === GCC NATIONAL POSTS ===
  empost: {
    id: 'empost',
    name: 'Emirates Post',
    nameAr: 'بريد الإمارات',
    country: 'UAE',
    logo: 'https://www.emiratespost.ae/images/logo.png',
    colors: {
      primary: '#C8102E',
      primaryDark: '#A00D24',
      primaryLight: '#DD2A4A',
      secondary: '#003087',
      secondaryDark: '#002666',
      secondaryLight: '#1A4DB8',
      accent: '#FFD700',
      background: '#FFFFFF',
      surface: '#F8F9FA',
      text: '#1A1A1A',
      textLight: '#666666',
      textOnPrimary: '#FFFFFF',
      border: '#E0E0E0',
      success: '#007A3D',
      warning: '#FFA500',
      error: '#DC2626',
    },
    gradients: {
      primary: 'linear-gradient(135deg, #C8102E 0%, #A00D24 100%)',
      secondary: 'linear-gradient(135deg, #003087 0%, #002666 100%)',
      accent: 'linear-gradient(90deg, #C8102E 0%, #003087 100%)',
    },
    fonts: {
      primary: 'Emirates Post Sans, Arial, sans-serif',
      primaryAr: 'Noto Kufi Arabic, Arial, sans-serif',
    },
    buttonStyles: {
      primary: 'bg-gradient-to-r from-red-700 to-blue-800 hover:from-red-800 hover:to-blue-900 text-white font-bold py-3 px-6 rounded-lg shadow-lg transition-all duration-300 transform hover:scale-105',
      secondary: 'bg-white border-2 border-red-700 text-red-700 hover:bg-red-50 font-bold py-3 px-6 rounded-lg',
      outline: 'bg-transparent border-2 border-gray-300 text-gray-700 hover:border-red-700 hover:text-red-700 font-semibold py-3 px-6 rounded-lg',
      link: 'text-red-700 hover:text-red-800 font-semibold underline-offset-4 hover:underline',
    },
    borderRadius: {
      sm: '6px',
      md: '10px',
      lg: '14px',
      xl: '20px',
    },
    shadows: {
      sm: '0 1px 3px rgba(200, 16, 46, 0.12)',
      md: '0 3px 6px rgba(200, 16, 46, 0.18)',
      lg: '0 6px 12px rgba(200, 16, 46, 0.24)',
      xl: '0 12px 24px rgba(200, 16, 46, 0.3)',
    },
    heroImage: '/og-empost.jpg',
    ogImage: '/og-empost.jpg',
    description: 'بريد الإمارات - المشغل الوطني للبريد في دولة الإمارات العربية المتحدة',
    website: 'https://www.emiratespost.ae',
    officialColors: ['#C8102E', '#003087', '#FFD700'],
  },

  smsa: {
    id: 'smsa',
    name: 'SMSA Express',
    nameAr: 'شركة الشحن الحديثة',
    country: 'Saudi',
    logo: 'https://www.smsaexpress.com/images/logo.png',
    colors: {
      primary: '#0066CC',
      primaryDark: '#0052A3',
      primaryLight: '#1A80E6',
      secondary: '#FF6600',
      secondaryDark: '#CC5200',
      secondaryLight: '#FF8533',
      accent: '#00A8E8',
      background: '#FFFFFF',
      surface: '#F8F9FA',
      text: '#1A1A1A',
      textLight: '#666666',
      textOnPrimary: '#FFFFFF',
      border: '#E0E0E0',
      success: '#007A3D',
      warning: '#FFA500',
      error: '#DC2626',
    },
    gradients: {
      primary: 'linear-gradient(135deg, #0066CC 0%, #0052A3 100%)',
      secondary: 'linear-gradient(135deg, #FF6600 0%, #CC5200 100%)',
      accent: 'linear-gradient(90deg, #0066CC 0%, #FF6600 100%)',
    },
    fonts: {
      primary: 'SMSA Sans, Arial, sans-serif',
      primaryAr: 'Noto Kufi Arabic, Arial, sans-serif',
    },
    buttonStyles: {
      primary: 'bg-gradient-to-r from-blue-600 to-orange-600 hover:from-blue-700 hover:to-orange-700 text-white font-bold py-3 px-6 rounded-lg shadow-lg transition-all duration-300 transform hover:scale-105',
      secondary: 'bg-white border-2 border-blue-600 text-blue-600 hover:bg-blue-50 font-bold py-3 px-6 rounded-lg',
      outline: 'bg-transparent border-2 border-gray-300 text-gray-700 hover:border-blue-600 hover:text-blue-600 font-semibold py-3 px-6 rounded-lg',
      link: 'text-blue-600 hover:text-blue-700 font-semibold underline-offset-4 hover:underline',
    },
    borderRadius: {
      sm: '4px',
      md: '8px',
      lg: '12px',
      xl: '16px',
    },
    shadows: {
      sm: '0 1px 3px rgba(0, 102, 204, 0.12)',
      md: '0 3px 6px rgba(0, 102, 204, 0.18)',
      lg: '0 6px 12px rgba(0, 102, 204, 0.24)',
      xl: '0 12px 24px rgba(0, 102, 204, 0.3)',
    },
    heroImage: '/og-smsa.jpg',
    ogImage: '/og-smsa.jpg',
    description: 'شركة الشحن الحديثة - أكبر شركة شحن سعودية',
    website: 'https://www.smsaexpress.com',
    officialColors: ['#0066CC', '#FF6600', '#00A8E8'],
  },

  zajil: {
    id: 'zajil',
    name: 'Zajil',
    nameAr: 'زاجل',
    country: 'Saudi',
    logo: 'https://zajil.com/assets/images/logo.png',
    colors: {
      primary: '#1C4587',
      primaryDark: '#16386B',
      primaryLight: '#2A5BA8',
      secondary: '#FF9900',
      secondaryDark: '#CC7A00',
      secondaryLight: '#FFB333',
      accent: '#00C9A7',
      background: '#FFFFFF',
      surface: '#F8F9FA',
      text: '#1A1A1A',
      textLight: '#666666',
      textOnPrimary: '#FFFFFF',
      border: '#E0E0E0',
      success: '#007A3D',
      warning: '#FFA500',
      error: '#DC2626',
    },
    gradients: {
      primary: 'linear-gradient(135deg, #1C4587 0%, #16386B 100%)',
      secondary: 'linear-gradient(135deg, #FF9900 0%, #CC7A00 100%)',
      accent: 'linear-gradient(90deg, #1C4587 0%, #FF9900 100%)',
    },
    fonts: {
      primary: 'Zajil Sans, Arial, sans-serif',
      primaryAr: 'Noto Kufi Arabic, Arial, sans-serif',
    },
    buttonStyles: {
      primary: 'bg-gradient-to-r from-blue-700 to-orange-600 hover:from-blue-800 hover:to-orange-700 text-white font-bold py-3 px-6 rounded-lg shadow-lg transition-all duration-300 transform hover:scale-105',
      secondary: 'bg-white border-2 border-blue-700 text-blue-700 hover:bg-blue-50 font-bold py-3 px-6 rounded-lg',
      outline: 'bg-transparent border-2 border-gray-300 text-gray-700 hover:border-blue-700 hover:text-blue-700 font-semibold py-3 px-6 rounded-lg',
      link: 'text-blue-700 hover:text-blue-800 font-semibold underline-offset-4 hover:underline',
    },
    borderRadius: {
      sm: '4px',
      md: '8px',
      lg: '12px',
      xl: '16px',
    },
    shadows: {
      sm: '0 1px 3px rgba(28, 69, 135, 0.12)',
      md: '0 3px 6px rgba(28, 69, 135, 0.18)',
      lg: '0 6px 12px rgba(28, 69, 135, 0.24)',
      xl: '0 12px 24px rgba(28, 69, 135, 0.3)',
    },
    heroImage: '/og-zajil.jpg',
    ogImage: '/og-zajil.jpg',
    description: 'زاجل - شركة سعودية رائدة في خدمات البريد السريع والشحن',
    website: 'https://zajil.com',
    officialColors: ['#1C4587', '#FF9900', '#00C9A7'],
  },

  naqel: {
    id: 'naqel',
    name: 'Naqel Express',
    nameAr: 'شركة ناقل إكسبريس',
    country: 'Saudi',
    logo: 'https://www.naqelexpress.com/images/logo.png',
    colors: {
      primary: '#0052A3',
      primaryDark: '#004082',
      primaryLight: '#1A75D9',
      secondary: '#FF6B00',
      secondaryDark: '#CC5600',
      secondaryLight: '#FF8C33',
      accent: '#00A8E8',
      background: '#FFFFFF',
      surface: '#F8F9FA',
      text: '#1A1A1A',
      textLight: '#666666',
      textOnPrimary: '#FFFFFF',
      border: '#E0E0E0',
      success: '#007A3D',
      warning: '#FFA500',
      error: '#DC2626',
    },
    gradients: {
      primary: 'linear-gradient(135deg, #0052A3 0%, #004082 100%)',
      secondary: 'linear-gradient(135deg, #FF6B00 0%, #CC5600 100%)',
      accent: 'linear-gradient(90deg, #0052A3 0%, #FF6B00 100%)',
    },
    fonts: {
      primary: 'Naqel Sans, Arial, sans-serif',
      primaryAr: 'Noto Kufi Arabic, Arial, sans-serif',
    },
    buttonStyles: {
      primary: 'bg-gradient-to-r from-blue-600 to-orange-600 hover:from-blue-700 hover:to-orange-700 text-white font-bold py-3 px-6 rounded-lg shadow-lg transition-all duration-300 transform hover:scale-105',
      secondary: 'bg-white border-2 border-blue-600 text-blue-600 hover:bg-blue-50 font-bold py-3 px-6 rounded-lg',
      outline: 'bg-transparent border-2 border-gray-300 text-gray-700 hover:border-blue-600 hover:text-blue-600 font-semibold py-3 px-6 rounded-lg',
      link: 'text-blue-600 hover:text-blue-700 font-semibold underline-offset-4 hover:underline',
    },
    borderRadius: {
      sm: '4px',
      md: '8px',
      lg: '12px',
      xl: '16px',
    },
    shadows: {
      sm: '0 1px 3px rgba(0, 82, 163, 0.12)',
      md: '0 3px 6px rgba(0, 82, 163, 0.18)',
      lg: '0 6px 12px rgba(0, 82, 163, 0.24)',
      xl: '0 12px 24px rgba(0, 82, 163, 0.3)',
    },
    heroImage: '/og-naqel.jpg',
    ogImage: '/og-naqel.jpg',
    description: 'ناقل إكسبريس - حلول شحن متطورة وخدمات لوجستية',
    website: 'https://www.naqelexpress.com',
    officialColors: ['#0052A3', '#FF6B00', '#00A8E8'],
  },

  saudipost: {
    id: 'saudipost',
    name: 'Saudi Post',
    nameAr: 'بريد السعودية',
    country: 'Saudi',
    logo: 'https://sp.com.sa/assets/images/logo.png',
    colors: {
      primary: '#006C35',
      primaryDark: '#005528',
      primaryLight: '#00A355',
      secondary: '#FFB81C',
      secondaryDark: '#CC9317',
      secondaryLight: '#FFD666',
      accent: '#000000',
      background: '#FFFFFF',
      surface: '#F8F9FA',
      text: '#1A1A1A',
      textLight: '#666666',
      textOnPrimary: '#FFFFFF',
      border: '#E0E0E0',
      success: '#007A3D',
      warning: '#FFA500',
      error: '#DC2626',
    },
    gradients: {
      primary: 'linear-gradient(135deg, #006C35 0%, #005528 100%)',
      secondary: 'linear-gradient(135deg, #FFB81C 0%, #CC9317 100%)',
      accent: 'linear-gradient(90deg, #006C35 0%, #FFB81C 100%)',
    },
    fonts: {
      primary: 'Saudi Post Sans, Arial, sans-serif',
      primaryAr: 'Noto Kufi Arabic, Arial, sans-serif',
    },
    buttonStyles: {
      primary: 'bg-gradient-to-r from-green-700 to-yellow-500 hover:from-green-800 hover:to-yellow-600 text-white font-bold py-3 px-6 rounded-lg shadow-lg transition-all duration-300 transform hover:scale-105',
      secondary: 'bg-white border-2 border-green-700 text-green-700 hover:bg-green-50 font-bold py-3 px-6 rounded-lg',
      outline: 'bg-transparent border-2 border-gray-300 text-gray-700 hover:border-green-700 hover:text-green-700 font-semibold py-3 px-6 rounded-lg',
      link: 'text-green-700 hover:text-green-800 font-semibold underline-offset-4 hover:underline',
    },
    borderRadius: {
      sm: '6px',
      md: '10px',
      lg: '14px',
      xl: '20px',
    },
    shadows: {
      sm: '0 1px 3px rgba(0, 108, 53, 0.12)',
      md: '0 3px 6px rgba(0, 108, 53, 0.18)',
      lg: '0 6px 12px rgba(0, 108, 53, 0.24)',
      xl: '0 12px 24px rgba(0, 108, 53, 0.3)',
    },
    heroImage: '/og-saudipost.jpg',
    ogImage: '/og-saudipost.jpg',
    description: 'بريد السعودية - المشغل الوطني للبريد في المملكة العربية السعودية',
    website: 'https://sp.com.sa',
    officialColors: ['#006C35', '#FFB81C', '#000000'],
  },

  kwpost: {
    id: 'kwpost',
    name: 'Kuwait Post',
    nameAr: 'بريد الكويت',
    country: 'Kuwait',
    logo: 'https://www.kwpost.com.kw/images/logo.png',
    colors: {
      primary: '#007A33',
      primaryDark: '#006029',
      primaryLight: '#00A355',
      secondary: '#DA291C',
      secondaryDark: '#AE2116',
      secondaryLight: '#E6453A',
      accent: '#FFD700',
      background: '#FFFFFF',
      surface: '#F8F9FA',
      text: '#1A1A1A',
      textLight: '#666666',
      textOnPrimary: '#FFFFFF',
      border: '#E0E0E0',
      success: '#007A3D',
      warning: '#FFA500',
      error: '#DC2626',
    },
    gradients: {
      primary: 'linear-gradient(135deg, #007A33 0%, #006029 100%)',
      secondary: 'linear-gradient(135deg, #DA291C 0%, #AE2116 100%)',
      accent: 'linear-gradient(90deg, #007A33 0%, #DA291C 100%)',
    },
    fonts: {
      primary: 'Kuwait Post Sans, Arial, sans-serif',
      primaryAr: 'Noto Kufi Arabic, Arial, sans-serif',
    },
    buttonStyles: {
      primary: 'bg-gradient-to-r from-green-700 to-red-700 hover:from-green-800 hover:to-red-800 text-white font-bold py-3 px-6 rounded-lg shadow-lg transition-all duration-300 transform hover:scale-105',
      secondary: 'bg-white border-2 border-green-700 text-green-700 hover:bg-green-50 font-bold py-3 px-6 rounded-lg',
      outline: 'bg-transparent border-2 border-gray-300 text-gray-700 hover:border-green-700 hover:text-green-700 font-semibold py-3 px-6 rounded-lg',
      link: 'text-green-700 hover:text-green-800 font-semibold underline-offset-4 hover:underline',
    },
    borderRadius: {
      sm: '6px',
      md: '10px',
      lg: '14px',
      xl: '20px',
    },
    shadows: {
      sm: '0 1px 3px rgba(0, 122, 51, 0.12)',
      md: '0 3px 6px rgba(0, 122, 51, 0.18)',
      lg: '0 6px 12px rgba(0, 122, 51, 0.24)',
      xl: '0 12px 24px rgba(0, 122, 51, 0.3)',
    },
    heroImage: '/og-kwpost.jpg',
    ogImage: '/og-kwpost.jpg',
    description: 'بريد الكويت - المشغل الوطني للبريد في دولة الكويت',
    website: 'https://www.kwpost.com.kw',
    officialColors: ['#007A33', '#DA291C', '#FFD700'],
  },

  qpost: {
    id: 'qpost',
    name: 'Qatar Post',
    nameAr: 'بريد قطر',
    country: 'Qatar',
    logo: 'https://www.qpost.qa/assets/images/logo.png',
    colors: {
      primary: '#8E1838',
      primaryDark: '#72132C',
      primaryLight: '#A82C50',
      secondary: '#FFFFFF',
      accent: '#C9A227',
      background: '#FFFFFF',
      surface: '#FAFAFA',
      text: '#1A1A1A',
      textLight: '#666666',
      textOnPrimary: '#FFFFFF',
      border: '#E0E0E0',
      success: '#007A3D',
      warning: '#FFA500',
      error: '#DC2626',
    },
    gradients: {
      primary: 'linear-gradient(135deg, #8E1838 0%, #72132C 100%)',
      secondary: 'linear-gradient(135deg, #FFFFFF 0%, #F5F5F5 100%)',
      accent: 'linear-gradient(90deg, #8E1838 0%, #C9A227 100%)',
    },
    fonts: {
      primary: 'Qatar Post Sans, Arial, sans-serif',
      primaryAr: 'Noto Kufi Arabic, Arial, sans-serif',
    },
    buttonStyles: {
      primary: 'bg-gradient-to-r from-red-800 to-red-900 hover:from-red-900 hover:to-red-950 text-white font-bold py-3 px-6 rounded-lg shadow-lg transition-all duration-300 transform hover:scale-105',
      secondary: 'bg-white border-2 border-red-800 text-red-800 hover:bg-red-50 font-bold py-3 px-6 rounded-lg',
      outline: 'bg-transparent border-2 border-gray-300 text-gray-700 hover:border-red-800 hover:text-red-800 font-semibold py-3 px-6 rounded-lg',
      link: 'text-red-800 hover:text-red-900 font-semibold underline-offset-4 hover:underline',
    },
    borderRadius: {
      sm: '6px',
      md: '10px',
      lg: '14px',
      xl: '20px',
    },
    shadows: {
      sm: '0 1px 3px rgba(142, 24, 56, 0.12)',
      md: '0 3px 6px rgba(142, 24, 56, 0.18)',
      lg: '0 6px 12px rgba(142, 24, 56, 0.24)',
      xl: '0 12px 24px rgba(142, 24, 56, 0.3)',
    },
    heroImage: '/og-qpost.jpg',
    ogImage: '/og-qpost.jpg',
    description: 'بريد قطر - المشغل الوطني للبريد في دولة قطر',
    website: 'https://www.qpost.qa',
    officialColors: ['#8E1838', '#FFFFFF', '#C9A227'],
  },

  omanpost: {
    id: 'omanpost',
    name: 'Oman Post',
    nameAr: 'بريد عُمان',
    country: 'Oman',
    logo: 'https://www.omanpost.om/images/logo.png',
    colors: {
      primary: '#ED1C24',
      primaryDark: '#C4151D',
      primaryLight: '#F1424E',
      secondary: '#009639',
      secondaryDark: '#00772D',
      secondaryLight: '#00B350',
      accent: '#C9A227',
      background: '#FFFFFF',
      surface: '#FAFAFA',
      text: '#1A1A1A',
      textLight: '#666666',
      textOnPrimary: '#FFFFFF',
      border: '#E0E0E0',
      success: '#007A3D',
      warning: '#FFA500',
      error: '#DC2626',
    },
    gradients: {
      primary: 'linear-gradient(135deg, #ED1C24 0%, #C4151D 100%)',
      secondary: 'linear-gradient(135deg, #009639 0%, #00772D 100%)',
      accent: 'linear-gradient(90deg, #ED1C24 0%, #009639 100%)',
    },
    fonts: {
      primary: 'Oman Post Sans, Arial, sans-serif',
      primaryAr: 'Noto Kufi Arabic, Arial, sans-serif',
    },
    buttonStyles: {
      primary: 'bg-gradient-to-r from-red-700 to-green-700 hover:from-red-800 hover:to-green-800 text-white font-bold py-3 px-6 rounded-lg shadow-lg transition-all duration-300 transform hover:scale-105',
      secondary: 'bg-white border-2 border-red-700 text-red-700 hover:bg-red-50 font-bold py-3 px-6 rounded-lg',
      outline: 'bg-transparent border-2 border-gray-300 text-gray-700 hover:border-red-700 hover:text-red-700 font-semibold py-3 px-6 rounded-lg',
      link: 'text-red-700 hover:text-red-800 font-semibold underline-offset-4 hover:underline',
    },
    borderRadius: {
      sm: '6px',
      md: '10px',
      lg: '14px',
      xl: '20px',
    },
    shadows: {
      sm: '0 1px 3px rgba(237, 28, 36, 0.12)',
      md: '0 3px 6px rgba(237, 28, 36, 0.18)',
      lg: '0 6px 12px rgba(237, 28, 36, 0.24)',
      xl: '0 12px 24px rgba(237, 28, 36, 0.3)',
    },
    heroImage: '/og-omanpost.jpg',
    ogImage: '/og-omanpost.jpg',
    description: 'بريد عُمان - المشغل الوطني للبريد في سلطنة عُمان',
    website: 'https://www.omanpost.om',
    officialColors: ['#ED1C24', '#009639', '#C9A227'],
  },

  bahpost: {
    id: 'bahpost',
    name: 'Bahrain Post',
    nameAr: 'بريد البحرين',
    country: 'Bahrain',
    logo: 'https://www.bahrainpost.gov.bh/images/logo.png',
    colors: {
      primary: '#CE1126',
      primaryDark: '#A80E1E',
      primaryLight: '#E12844',
      secondary: '#FFFFFF',
      accent: '#C9A227',
      background: '#FFFFFF',
      surface: '#FAFAFA',
      text: '#1A1A1A',
      textLight: '#666666',
      textOnPrimary: '#FFFFFF',
      border: '#E0E0E0',
      success: '#007A3D',
      warning: '#FFA500',
      error: '#DC2626',
    },
    gradients: {
      primary: 'linear-gradient(135deg, #CE1126 0%, #A80E1E 100%)',
      secondary: 'linear-gradient(135deg, #FFFFFF 0%, #F5F5F5 100%)',
      accent: 'linear-gradient(90deg, #CE1126 0%, #C9A227 100%)',
    },
    fonts: {
      primary: 'Bahrain Post Sans, Arial, sans-serif',
      primaryAr: 'Noto Kufi Arabic, Arial, sans-serif',
    },
    buttonStyles: {
      primary: 'bg-gradient-to-r from-red-700 to-red-800 hover:from-red-800 hover:to-red-900 text-white font-bold py-3 px-6 rounded-lg shadow-lg transition-all duration-300 transform hover:scale-105',
      secondary: 'bg-white border-2 border-red-700 text-red-700 hover:bg-red-50 font-bold py-3 px-6 rounded-lg',
      outline: 'bg-transparent border-2 border-gray-300 text-gray-700 hover:border-red-700 hover:text-red-700 font-semibold py-3 px-6 rounded-lg',
      link: 'text-red-700 hover:text-red-800 font-semibold underline-offset-4 hover:underline',
    },
    borderRadius: {
      sm: '6px',
      md: '10px',
      lg: '14px',
      xl: '20px',
    },
    shadows: {
      sm: '0 1px 3px rgba(206, 17, 38, 0.12)',
      md: '0 3px 6px rgba(206, 17, 38, 0.18)',
      lg: '0 6px 12px rgba(206, 17, 38, 0.24)',
      xl: '0 12px 24px rgba(206, 17, 38, 0.3)',
    },
    heroImage: '/og-bahpost.jpg',
    ogImage: '/og-bahpost.jpg',
    description: 'بريد البحرين - المشغل الوطني للبريد في مملكة البحرين',
    website: 'https://www.bahrainpost.gov.bh',
    officialColors: ['#CE1126', '#FFFFFF', '#C9A227'],
  },

  // === REGIONAL LOGISTICS COMPANIES ===
  albaraka: {
    id: 'albaraka',
    name: 'Al Baraka',
    nameAr: 'البركة',
    country: 'GCC',
    logo: 'https://logo.clearbit.com/albaraka.com.tr',
    colors: {
      primary: '#D89A00',
      primaryDark: '#B87D00',
      primaryLight: '#F0B833',
      secondary: '#FFFFFF',
      accent: '#C9A227',
      background: '#FFFFFF',
      surface: '#FAFAFA',
      text: '#1A1A1A',
      textLight: '#666666',
      textOnPrimary: '#FFFFFF',
      border: '#E0E0E0',
      success: '#007A3D',
      warning: '#FFA500',
      error: '#DC2626',
    },
    gradients: {
      primary: 'linear-gradient(135deg, #D89A00 0%, #B87D00 100%)',
      secondary: 'linear-gradient(135deg, #FFFFFF 0%, #F5F5F5 100%)',
      accent: 'linear-gradient(90deg, #D89A00 0%, #C9A227 100%)',
    },
    fonts: {
      primary: 'Al Baraka Sans, Arial, sans-serif',
      primaryAr: 'Noto Kufi Arabic, Arial, sans-serif',
    },
    buttonStyles: {
      primary: 'bg-gradient-to-r from-yellow-600 to-yellow-700 hover:from-yellow-700 hover:to-yellow-800 text-white font-bold py-3 px-6 rounded-lg shadow-lg transition-all duration-300 transform hover:scale-105',
      secondary: 'bg-white border-2 border-yellow-600 text-yellow-700 hover:bg-yellow-50 font-bold py-3 px-6 rounded-lg',
      outline: 'bg-transparent border-2 border-gray-300 text-gray-700 hover:border-yellow-600 hover:text-yellow-600 font-semibold py-3 px-6 rounded-lg',
      link: 'text-yellow-700 hover:text-yellow-800 font-semibold underline-offset-4 hover:underline',
    },
    borderRadius: {
      sm: '4px',
      md: '8px',
      lg: '12px',
      xl: '16px',
    },
    shadows: {
      sm: '0 1px 3px rgba(216, 154, 0, 0.12)',
      md: '0 3px 6px rgba(216, 154, 0, 0.18)',
      lg: '0 6px 12px rgba(216, 154, 0, 0.24)',
      xl: '0 12px 24px rgba(216, 154, 0, 0.3)',
    },
    heroImage: '/og-albaraka.jpg',
    ogImage: '/og-albaraka.jpg',
    description: 'مجموعة البركة - خدمات شحن وبنكية متكاملة',
    website: 'https://albaraka.com.tr',
    officialColors: ['#D89A00', '#FFFFFF', '#C9A227'],
  },

  alfuttaim: {
    id: 'alfuttaim',
    name: 'Al-Futtaim',
    nameAr: 'الفطيم',
    country: 'UAE',
    logo: 'https://logo.clearbit.com/alfuttaim.com',
    colors: {
      primary: '#00559B',
      primaryDark: '#00427A',
      primaryLight: '#1A75D9',
      secondary: '#FFFFFF',
      accent: '#C9A227',
      background: '#FFFFFF',
      surface: '#FAFAFA',
      text: '#1A1A1A',
      textLight: '#666666',
      textOnPrimary: '#FFFFFF',
      border: '#E0E0E0',
      success: '#007A3D',
      warning: '#FFA500',
      error: '#DC2626',
    },
    gradients: {
      primary: 'linear-gradient(135deg, #00559B 0%, #00427A 100%)',
      secondary: 'linear-gradient(135deg, #FFFFFF 0%, #F5F5F5 100%)',
      accent: 'linear-gradient(90deg, #00559B 0%, #C9A227 100%)',
    },
    fonts: {
      primary: 'Al-Futtaim Sans, Arial, sans-serif',
      primaryAr: 'Noto Kufi Arabic, Arial, sans-serif',
    },
    buttonStyles: {
      primary: 'bg-gradient-to-r from-blue-700 to-blue-800 hover:from-blue-800 hover:to-blue-900 text-white font-bold py-3 px-6 rounded-lg shadow-lg transition-all duration-300 transform hover:scale-105',
      secondary: 'bg-white border-2 border-blue-700 text-blue-700 hover:bg-blue-50 font-bold py-3 px-6 rounded-lg',
      outline: 'bg-transparent border-2 border-gray-300 text-gray-700 hover:border-blue-700 hover:text-blue-700 font-semibold py-3 px-6 rounded-lg',
      link: 'text-blue-700 hover:text-blue-800 font-semibold underline-offset-4 hover:underline',
    },
    borderRadius: {
      sm: '4px',
      md: '8px',
      lg: '12px',
      xl: '16px',
    },
    shadows: {
      sm: '0 1px 3px rgba(0, 85, 155, 0.12)',
      md: '0 3px 6px rgba(0, 85, 155, 0.18)',
      lg: '0 6px 12px rgba(0, 85, 155, 0.24)',
      xl: '0 12px 24px rgba(0, 85, 155, 0.3)',
    },
    heroImage: '/og-alfuttaim.jpg',
    ogImage: '/og-alfuttaim.jpg',
    description: 'مجموعة الفطيم - حلول لوجستية متكاملة',
    website: 'https://alfuttaim.com',
    officialColors: ['#00559B', '#FFFFFF', '#C9A227'],
  },

  alshaya: {
    id: 'alshaya',
    name: 'Al-Shaya',
    nameAr: 'الشايع',
    country: 'GCC',
    logo: 'https://logo.clearbit.com/alshaya.com',
    colors: {
      primary: '#D71920',
      primaryDark: '#AB1219',
      primaryLight: '#E83A44',
      secondary: '#000000',
      accent: '#C9A227',
      background: '#FFFFFF',
      surface: '#FAFAFA',
      text: '#1A1A1A',
      textLight: '#666666',
      textOnPrimary: '#FFFFFF',
      border: '#E0E0E0',
      success: '#007A3D',
      warning: '#FFA500',
      error: '#DC2626',
    },
    gradients: {
      primary: 'linear-gradient(135deg, #D71920 0%, #AB1219 100%)',
      secondary: 'linear-gradient(135deg, #000000 0%, #1A1A1A 100%)',
      accent: 'linear-gradient(90deg, #D71920 0%, #C9A227 100%)',
    },
    fonts: {
      primary: 'Al-Shaya Sans, Arial, sans-serif',
      primaryAr: 'Noto Kufi Arabic, Arial, sans-serif',
    },
    buttonStyles: {
      primary: 'bg-gradient-to-r from-red-700 to-red-800 hover:from-red-800 hover:to-red-900 text-white font-bold py-3 px-6 rounded-lg shadow-lg transition-all duration-300 transform hover:scale-105',
      secondary: 'bg-black hover:bg-gray-800 text-white font-bold py-3 px-6 rounded-lg',
      outline: 'bg-transparent border-2 border-gray-300 text-gray-700 hover:border-red-700 hover:text-red-700 font-semibold py-3 px-6 rounded-lg',
      link: 'text-red-700 hover:text-red-800 font-semibold underline-offset-4 hover:underline',
    },
    borderRadius: {
      sm: '4px',
      md: '8px',
      lg: '12px',
      xl: '16px',
    },
    shadows: {
      sm: '0 1px 3px rgba(215, 25, 32, 0.12)',
      md: '0 3px 6px rgba(215, 25, 32, 0.18)',
      lg: '0 6px 12px rgba(215, 25, 32, 0.24)',
      xl: '0 12px 24px rgba(215, 25, 32, 0.3)',
    },
    heroImage: '/og-alshaya.jpg',
    ogImage: '/og-alshaya.jpg',
    description: 'مجموعة الشايع - حلول التوزيع واللوجستيات',
    website: 'https://alshaya.com',
    officialColors: ['#D71920', '#000000', '#C9A227'],
  },

  national: {
    id: 'national',
    name: 'Bahri',
    nameAr: 'بحري',
    country: 'Saudi',
    logo: 'https://logo.clearbit.com/bahri.sa',
    colors: {
      primary: '#003366',
      primaryDark: '#00264D',
      primaryLight: '#1A4D99',
      secondary: '#FFFFFF',
      accent: '#C9A227',
      background: '#FFFFFF',
      surface: '#FAFAFA',
      text: '#1A1A1A',
      textLight: '#666666',
      textOnPrimary: '#FFFFFF',
      border: '#E0E0E0',
      success: '#007A3D',
      warning: '#FFA500',
      error: '#DC2626',
    },
    gradients: {
      primary: 'linear-gradient(135deg, #003366 0%, #00264D 100%)',
      secondary: 'linear-gradient(135deg, #FFFFFF 0%, #F5F5F5 100%)',
      accent: 'linear-gradient(90deg, #003366 0%, #C9A227 100%)',
    },
    fonts: {
      primary: 'Bahri Sans, Arial, sans-serif',
      primaryAr: 'Noto Kufi Arabic, Arial, sans-serif',
    },
    buttonStyles: {
      primary: 'bg-gradient-to-r from-blue-800 to-blue-900 hover:from-blue-900 hover:to-blue-950 text-white font-bold py-3 px-6 rounded-lg shadow-lg transition-all duration-300 transform hover:scale-105',
      secondary: 'bg-white border-2 border-blue-800 text-blue-800 hover:bg-blue-50 font-bold py-3 px-6 rounded-lg',
      outline: 'bg-transparent border-2 border-gray-300 text-gray-700 hover:border-blue-800 hover:text-blue-800 font-semibold py-3 px-6 rounded-lg',
      link: 'text-blue-800 hover:text-blue-900 font-semibold underline-offset-4 hover:underline',
    },
    borderRadius: {
      sm: '4px',
      md: '8px',
      lg: '12px',
      xl: '16px',
    },
    shadows: {
      sm: '0 1px 3px rgba(0, 51, 102, 0.12)',
      md: '0 3px 6px rgba(0, 51, 102, 0.18)',
      lg: '0 6px 12px rgba(0, 51, 102, 0.24)',
      xl: '0 12px 24px rgba(0, 51, 102, 0.3)',
    },
    heroImage: '/og-bahri.jpg',
    ogImage: '/og-bahri.jpg',
    description: 'بحري - خدمات شحن وبحرية ولوجستيات شاملة',
    website: 'https://bahri.sa',
    officialColors: ['#003366', '#FFFFFF', '#C9A227'],
  },

  shipco: {
    id: 'shipco',
    name: 'Shipco',
    nameAr: 'شيبكو',
    country: 'International',
    logo: 'https://logo.clearbit.com/shipco.com',
    colors: {
      primary: '#0A5FB4',
      primaryDark: '#084A8F',
      primaryLight: '#2A7BD1',
      secondary: '#FFFFFF',
      accent: '#00A8E8',
      background: '#FFFFFF',
      surface: '#FAFAFA',
      text: '#1A1A1A',
      textLight: '#666666',
      textOnPrimary: '#FFFFFF',
      border: '#E0E0E0',
      success: '#007A3D',
      warning: '#FFA500',
      error: '#DC2626',
    },
    gradients: {
      primary: 'linear-gradient(135deg, #0A5FB4 0%, #084A8F 100%)',
      secondary: 'linear-gradient(135deg, #FFFFFF 0%, #F5F5F5 100%)',
      accent: 'linear-gradient(90deg, #0A5FB4 0%, #00A8E8 100%)',
    },
    fonts: {
      primary: 'Shipco Sans, Arial, sans-serif',
      primaryAr: 'Noto Kufi Arabic, Arial, sans-serif',
    },
    buttonStyles: {
      primary: 'bg-gradient-to-r from-blue-600 to-blue-700 hover:from-blue-700 hover:to-blue-800 text-white font-bold py-3 px-6 rounded-lg shadow-lg transition-all duration-300 transform hover:scale-105',
      secondary: 'bg-white border-2 border-blue-600 text-blue-600 hover:bg-blue-50 font-bold py-3 px-6 rounded-lg',
      outline: 'bg-transparent border-2 border-gray-300 text-gray-700 hover:border-blue-600 hover:text-blue-600 font-semibold py-3 px-6 rounded-lg',
      link: 'text-blue-600 hover:text-blue-700 font-semibold underline-offset-4 hover:underline',
    },
    borderRadius: {
      sm: '4px',
      md: '8px',
      lg: '12px',
      xl: '16px',
    },
    shadows: {
      sm: '0 1px 3px rgba(10, 95, 180, 0.12)',
      md: '0 3px 6px rgba(10, 95, 180, 0.18)',
      lg: '0 6px 12px rgba(10, 95, 180, 0.24)',
      xl: '0 12px 24px rgba(10, 95, 180, 0.3)',
    },
    heroImage: '/og-shipco.jpg',
    ogImage: '/og-shipco.jpg',
    description: 'شيبكو - خدمات شحن دولي ومحلي متخصص',
    website: 'https://www.shipco.com',
    officialColors: ['#0A5FB4', '#FFFFFF', '#00A8E8'],
  },

  hellmann: {
    id: 'hellmann',
    name: 'Hellmann',
    nameAr: 'هيلمان',
    country: 'International',
    logo: 'https://logo.clearbit.com/hellmann.com',
    colors: {
      primary: '#0C4DA2',
      primaryDark: '#093D7F',
      primaryLight: '#2A6BC5',
      secondary: '#FFFFFF',
      accent: '#C9A227',
      background: '#FFFFFF',
      surface: '#FAFAFA',
      text: '#1A1A1A',
      textLight: '#666666',
      textOnPrimary: '#FFFFFF',
      border: '#E0E0E0',
      success: '#007A3D',
      warning: '#FFA500',
      error: '#DC2626',
    },
    gradients: {
      primary: 'linear-gradient(135deg, #0C4DA2 0%, #093D7F 100%)',
      secondary: 'linear-gradient(135deg, #FFFFFF 0%, #F5F5F5 100%)',
      accent: 'linear-gradient(90deg, #0C4DA2 0%, #C9A227 100%)',
    },
    fonts: {
      primary: 'Hellmann Sans, Arial, sans-serif',
      primaryAr: 'Noto Kufi Arabic, Arial, sans-serif',
    },
    buttonStyles: {
      primary: 'bg-gradient-to-r from-blue-700 to-blue-800 hover:from-blue-800 hover:to-blue-900 text-white font-bold py-3 px-6 rounded-lg shadow-lg transition-all duration-300 transform hover:scale-105',
      secondary: 'bg-white border-2 border-blue-700 text-blue-700 hover:bg-blue-50 font-bold py-3 px-6 rounded-lg',
      outline: 'bg-transparent border-2 border-gray-300 text-gray-700 hover:border-blue-700 hover:text-blue-700 font-semibold py-3 px-6 rounded-lg',
      link: 'text-blue-700 hover:text-blue-800 font-semibold underline-offset-4 hover:underline',
    },
    borderRadius: {
      sm: '4px',
      md: '8px',
      lg: '12px',
      xl: '16px',
    },
    shadows: {
      sm: '0 1px 3px rgba(12, 77, 162, 0.12)',
      md: '0 3px 6px rgba(12, 77, 162, 0.18)',
      lg: '0 6px 12px rgba(12, 77, 162, 0.24)',
      xl: '0 12px 24px rgba(12, 77, 162, 0.3)',
    },
    heroImage: '/og-hellmann.jpg',
    ogImage: '/og-hellmann.jpg',
    description: 'هيلمان - شبكة دولية لخدمات الشحن واللوجستيات',
    website: 'https://www.hellmann.com',
    officialColors: ['#0C4DA2', '#FFFFFF', '#C9A227'],
  },

  dsv: {
    id: 'dsv',
    name: 'DSV',
    nameAr: 'دي إس في',
    country: 'International',
    logo: 'https://logo.clearbit.com/dsv.com',
    colors: {
      primary: '#0056A6',
      primaryDark: '#004285',
      primaryLight: '#1A75D9',
      secondary: '#FFFFFF',
      accent: '#C9A227',
      background: '#FFFFFF',
      surface: '#FAFAFA',
      text: '#1A1A1A',
      textLight: '#666666',
      textOnPrimary: '#FFFFFF',
      border: '#E0E0E0',
      success: '#007A3D',
      warning: '#FFA500',
      error: '#DC2626',
    },
    gradients: {
      primary: 'linear-gradient(135deg, #0056A6 0%, #004285 100%)',
      secondary: 'linear-gradient(135deg, #FFFFFF 0%, #F5F5F5 100%)',
      accent: 'linear-gradient(90deg, #0056A6 0%, #C9A227 100%)',
    },
    fonts: {
      primary: 'DSV Sans, Arial, sans-serif',
      primaryAr: 'Noto Kufi Arabic, Arial, sans-serif',
    },
    buttonStyles: {
      primary: 'bg-gradient-to-r from-blue-600 to-blue-700 hover:from-blue-700 hover:to-blue-800 text-white font-bold py-3 px-6 rounded-lg shadow-lg transition-all duration-300 transform hover:scale-105',
      secondary: 'bg-white border-2 border-blue-600 text-blue-600 hover:bg-blue-50 font-bold py-3 px-6 rounded-lg',
      outline: 'bg-transparent border-2 border-gray-300 text-gray-700 hover:border-blue-600 hover:text-blue-600 font-semibold py-3 px-6 rounded-lg',
      link: 'text-blue-600 hover:text-blue-700 font-semibold underline-offset-4 hover:underline',
    },
    borderRadius: {
      sm: '4px',
      md: '8px',
      lg: '12px',
      xl: '16px',
    },
    shadows: {
      sm: '0 1px 3px rgba(0, 86, 166, 0.12)',
      md: '0 3px 6px rgba(0, 86, 166, 0.18)',
      lg: '0 6px 12px rgba(0, 86, 166, 0.24)',
      xl: '0 12px 24px rgba(0, 86, 166, 0.3)',
    },
    heroImage: '/og-dsv.jpg',
    ogImage: '/og-dsv.jpg',
    description: 'دي إس في - حلول شحن ولوجستيات متطورة',
    website: 'https://www.dsv.com',
    officialColors: ['#0056A6', '#FFFFFF', '#C9A227'],
  },

  // === LOCAL COMPANIES ===
  jinaken: {
    id: 'jinaken',
    name: 'Jinaken',
    nameAr: 'جناكن',
    country: 'Oman',
    logo: '/og-jinaken.jpg',
    colors: {
      primary: '#E82424',
      primaryDark: '#C01D1D',
      primaryLight: '#F35050',
      secondary: '#F7C24A',
      accent: '#C9A227',
      background: '#FFFFFF',
      surface: '#FAFAFA',
      text: '#1A1A1A',
      textLight: '#666666',
      textOnPrimary: '#FFFFFF',
      border: '#E0E0E0',
      success: '#007A3D',
      warning: '#FFA500',
      error: '#DC2626',
    },
    gradients: {
      primary: 'linear-gradient(135deg, #E82424 0%, #C01D1D 100%)',
      secondary: 'linear-gradient(135deg, #F7C24A 0%, #E6B035 100%)',
      accent: 'linear-gradient(90deg, #E82424 0%, #F7C24A 100%)',
    },
    fonts: {
      primary: 'Jinaken Sans, Arial, sans-serif',
      primaryAr: 'Noto Kufi Arabic, Arial, sans-serif',
    },
    buttonStyles: {
      primary: 'bg-gradient-to-r from-red-600 to-yellow-500 hover:from-red-700 hover:to-yellow-600 text-white font-bold py-3 px-6 rounded-lg shadow-lg transition-all duration-300 transform hover:scale-105',
      secondary: 'bg-white border-2 border-red-600 text-red-600 hover:bg-red-50 font-bold py-3 px-6 rounded-lg',
      outline: 'bg-transparent border-2 border-gray-300 text-gray-700 hover:border-red-600 hover:text-red-600 font-semibold py-3 px-6 rounded-lg',
      link: 'text-red-600 hover:text-red-700 font-semibold underline-offset-4 hover:underline',
    },
    borderRadius: {
      sm: '4px',
      md: '8px',
      lg: '12px',
      xl: '16px',
    },
    shadows: {
      sm: '0 1px 3px rgba(232, 36, 36, 0.12)',
      md: '0 3px 6px rgba(232, 36, 36, 0.18)',
      lg: '0 6px 12px rgba(232, 36, 36, 0.24)',
      xl: '0 12px 24px rgba(232, 36, 36, 0.3)',
    },
    heroImage: '/og-jinaken.jpg',
    ogImage: '/og-genacom.jpg',
    description: 'جناكن - شركة توصيل عُمانية محلية',
    website: '',
    officialColors: ['#E82424', '#F7C24A', '#C9A227'],
  },
};

export const getCompanyBranding = (companyId: string): CompanyBranding => {
  const key = companyId.toLowerCase();
  return COMPANY_BRANDINGS[key] || COMPANY_BRANDINGS['aramex'];
};

export const getAllCompanies = (): CompanyBranding[] => {
  return Object.values(COMPANY_BRANDINGS);
};

export const getCompaniesByCountry = (country: string): CompanyBranding[] => {
  return Object.values(COMPANY_BRANDINGS).filter(
    (company) => company.country === country
  );
};
