// Official Company Branding - Pixel-Perfect Visual Twins
// Authentic designs matching real payment/checkout pages of each company
// All colors, fonts, buttons, and design elements replicate official brand identity

export interface CompanyBranding {
  id: string;
  name: string;
  nameAr: string;
  country: string;
  logo: string;
  logoLight?: string;
  favicon?: string;
  colors: {
    primary: string;
    primaryDark?: string;
    primaryLight?: string;
    secondary: string;
    secondaryDark?: string;
    secondaryLight?: string;
    accent: string;
    accentDark?: string;
    background: string;
    surface: string;
    text: string;
    textLight: string;
    textOnPrimary: string;
    border: string;
    success: string;
    warning: string;
    error: string;
  };
  gradients: {
    primary: string;
    secondary: string;
    accent: string;
  };
  fonts: {
    primary: string;
    primaryAr?: string;
    heading?: string;
    headingAr?: string;
  };
  buttonStyles: {
    primary: string;
    secondary: string;
    outline: string;
    link: string;
  };
  borderRadius: {
    sm: string;
    md: string;
    lg: string;
    xl: string;
  };
  shadows: {
    sm: string;
    md: string;
    lg: string;
    xl: string;
  };
  heroImage: string;
  ogImage: string;
  description: string;
  website?: string;
  officialColors?: string[];
}

export const COMPANY_BRANDINGS: Record<string, CompanyBranding> = {
  // === INTERNATIONAL EXPRESS ===
  aramex: {
    id: 'aramex',
    name: 'Aramex',
    nameAr: 'أرامكس',
    country: 'UAE',
    logo: 'https://www.aramex.com/content/aramex/en/homepage-3/_jcr_content/content/mainheader/logo.img.png/1549537864385.png',
    colors: {
      primary: '#E31E24',
      primaryDark: '#D10F17',
      primaryLight: '#FF2A3A',
      secondary: '#2C2C2C',
      secondaryDark: '#1A1A1A',
      secondaryLight: '#404040',
      accent: '#FF6600',
      background: '#FFFFFF',
      surface: '#FFFFFF',
      text: '#1A1A1A',
      textLight: '#666666',
      textOnPrimary: '#FFFFFF',
      border: '#E0E0E0',
      success: '#00A86B',
      warning: '#FFA500',
      error: '#DC2626',
    },
    gradients: {
      primary: 'linear-gradient(135deg, #E31E24 0%, #D10F17 100%)',
      secondary: 'linear-gradient(135deg, #2C2C2C 0%, #1A1A1A 100%)',
      accent: 'linear-gradient(90deg, #FF6600 0%, #E65C00 100%)',
    },
    fonts: {
      primary: 'Neo Sans, Arial, sans-serif',
      primaryAr: 'Noto Kufi Arabic, Arial, sans-serif',
      heading: 'Neo Sans Bold, Arial, sans-serif',
      headingAr: 'Noto Kufi Arabic Bold, Arial, sans-serif',
    },
    buttonStyles: {
      primary: 'background: linear-gradient(135deg, #E31E24 0%, #D10F17 100%); border-radius: 6px; font-weight: 500; padding: 14px 28px; box-shadow: 0 2px 8px rgba(227, 30, 36, 0.3);',
      secondary: 'background: #FFFFFF; border: 2px solid #E31E24; border-radius: 6px; color: #E31E24; font-weight: 500; padding: 14px 28px;',
      outline: 'background: transparent; border: 2px solid #2C2C2C; border-radius: 6px; color: #2C2C2C; padding: 14px 28px;',
      link: 'background: transparent; color: #E31E24; text-decoration: underline; padding: 0;',
    },
    borderRadius: {
      sm: '4px',
      md: '6px',
      lg: '8px',
      xl: '12px',
    },
    shadows: {
      sm: '0 1px 3px rgba(0, 0, 0, 0.12)',
      md: '0 2px 8px rgba(0, 0, 0, 0.15)',
      lg: '0 4px 16px rgba(0, 0, 0, 0.18)',
      xl: '0 8px 32px rgba(0, 0, 0, 0.22)',
    },
    heroImage: '/hero-aramex-48F6rlGC.jpg',
    ogImage: '/og-aramex.jpg',
    description: 'Leading logistics and transportation company in the Middle East',
    website: 'https://www.aramex.com',
    officialColors: ['#E31E24', '#2C2C2C', '#FF6600'],
  },

  ups: {
    id: 'ups',
    name: 'UPS',
    nameAr: 'يو بي إس',
    country: 'USA',
    logo: 'https://www.ups.com/assets/resources/images/ups-logo.svg',
    colors: {
      primary: '#5C3A21',
      primaryDark: '#3E2723',
      primaryLight: '#7B5E52',
      secondary: '#FFB500',
      secondaryDark: '#DAA520',
      secondaryLight: '#FFD700',
      accent: '#FFFFFF',
      background: '#FFFFFF',
      surface: '#F5F5F5',
      text: '#1A1A1A',
      textLight: '#666666',
      textOnPrimary: '#FFFFFF',
      border: '#E0E0E0',
      success: '#00A86B',
      warning: '#FFB500',
      error: '#DC2626',
    },
    gradients: {
      primary: 'linear-gradient(135deg, #5C3A21 0%, #3E2723 100%)',
      secondary: 'linear-gradient(135deg, #FFB500 0%, #DAA520 100%)',
      accent: 'linear-gradient(90deg, #5C3A21 0%, #7B5E52 100%)',
    },
    fonts: {
      primary: 'UPS Sans, Helvetica, Arial, sans-serif',
      primaryAr: 'Noto Kufi Arabic, Helvetica, Arial, sans-serif',
      heading: 'UPS Sans Bold, Helvetica, Arial, sans-serif',
      headingAr: 'Noto Kufi Arabic Bold, Helvetica, Arial, sans-serif',
    },
    buttonStyles: {
      primary: 'background: linear-gradient(135deg, #5C3A21 0%, #3E2723 100%); border-radius: 6px; font-weight: 600; padding: 14px 32px; box-shadow: 0 2px 8px rgba(92, 58, 33, 0.3);',
      secondary: 'background: #FFB500; border: none; border-radius: 6px; color: #1A1A1A; font-weight: 600; padding: 14px 32px;',
      outline: 'background: transparent; border: 2px solid #5C3A21; border-radius: 6px; color: #5C3A21; padding: 14px 32px;',
      link: 'background: transparent; color: #5C3A21; text-decoration: underline; padding: 0;',
    },
    borderRadius: {
      sm: '4px',
      md: '6px',
      lg: '8px',
      xl: '12px',
    },
    shadows: {
      sm: '0 1px 3px rgba(0, 0, 0, 0.12)',
      md: '0 2px 8px rgba(0, 0, 0, 0.15)',
      lg: '0 4px 16px rgba(0, 0, 0, 0.18)',
      xl: '0 8px 32px rgba(0, 0, 0, 0.22)',
    },
    heroImage: '/hero-ups-CNM66VBg.jpg',
    ogImage: '/og-ups.jpg',
    description: 'World\'s largest package delivery company',
    website: 'https://www.ups.com',
    officialColors: ['#5C3A21', '#FFB500', '#FFFFFF'],
  },

  fedex: {
    id: 'fedex',
    name: 'FedEx',
    nameAr: 'فيديكس',
    country: 'USA',
    logo: 'https://logos-world.net/wp-content/uploads/2023/01/FedEx-Emblem.png',
    colors: {
      primary: '#4D148C',
      primaryDark: '#3E0F6F',
      primaryLight: '#5E1E8C',
      secondary: '#FF6600',
      secondaryDark: '#E65C00',
      secondaryLight: '#FF8533',
      accent: '#FFCC00',
      background: '#FFFFFF',
      surface: '#F5F5F5',
      text: '#333333',
      textLight: '#666666',
      textOnPrimary: '#FFFFFF',
      border: '#E0E0E0',
      success: '#00A86B',
      warning: '#FFA500',
      error: '#DC2626',
    },
    gradients: {
      primary: 'linear-gradient(135deg, #4D148C 0%, #3E0F6F 100%)',
      secondary: 'linear-gradient(135deg, #FF6600 0%, #E65C00 100%)',
      accent: 'linear-gradient(90deg, #FFCC00 0%, #FFB500 100%)',
    },
    fonts: {
      primary: 'FedEx Sans, Open Sans, Helvetica, Arial, sans-serif',
      primaryAr: 'Noto Kufi Arabic, Open Sans, Arial, sans-serif',
      heading: 'FedEx Sans Medium, Open Sans, Helvetica, Arial, sans-serif',
      headingAr: 'Noto Kufi Arabic Medium, Open Sans, Arial, sans-serif',
    },
    buttonStyles: {
      primary: 'background: linear-gradient(135deg, #4D148C 0%, #3E0F6F 100%); border-radius: 8px; font-weight: 500; padding: 14px 28px; box-shadow: 0 2px 8px rgba(77, 20, 140, 0.3);',
      secondary: 'background: #FF6600; border: none; border-radius: 8px; color: #FFFFFF; font-weight: 500; padding: 14px 28px;',
      outline: 'background: transparent; border: 2px solid #4D148C; border-radius: 8px; color: #4D148C; padding: 14px 28px;',
      link: 'background: transparent; color: #4D148C; text-decoration: underline; padding: 0;',
    },
    borderRadius: {
      sm: '4px',
      md: '8px',
      lg: '10px',
      xl: '14px',
    },
    shadows: {
      sm: '0 1px 3px rgba(0, 0, 0, 0.12)',
      md: '0 2px 8px rgba(0, 0, 0, 0.15)',
      lg: '0 4px 16px rgba(0, 0, 0, 0.18)',
      xl: '0 8px 32px rgba(0, 0, 0, 0.22)',
    },
    heroImage: '/hero-fedex-DGkmuzW9.jpg',
    ogImage: '/og-fedex.jpg',
    description: 'Multinational courier delivery services company',
    website: 'https://www.fedex.com',
    officialColors: ['#4D148C', '#FF6600', '#FFCC00'],
  },

  dhl: {
    id: 'dhl',
    name: 'DHL',
    nameAr: 'دي إتش إل',
    country: 'Germany',
    logo: 'https://www.dhl.com/content/dam/dhlglobal/ClsGlobal/global/logos/logos-dhl.svg',
    colors: {
      primary: '#D40511',
      primaryDark: '#B3030E',
      primaryLight: '#E30613',
      secondary: '#FFCD00',
      secondaryDark: '#DAA520',
      secondaryLight: '#FFD700',
      accent: '#000000',
      background: '#FFFFFF',
      surface: '#F5F5F5',
      text: '#2B2B2B',
      textLight: '#666666',
      textOnPrimary: '#FFFFFF',
      border: '#E0E0E0',
      success: '#00A86B',
      warning: '#FFCD00',
      error: '#DC2626',
    },
    gradients: {
      primary: 'linear-gradient(135deg, #D40511 0%, #B3030E 100%)',
      secondary: 'linear-gradient(135deg, #FFCD00 0%, #DAA520 100%)',
      accent: 'linear-gradient(90deg, #000000 0%, #2B2B2B 100%)',
    },
    fonts: {
      primary: 'DHL Display, Helvetica Neue, Arial, sans-serif',
      primaryAr: 'Noto Kufi Arabic, Helvetica Neue, Arial, sans-serif',
      heading: 'DHL Display Bold, Helvetica Neue, Arial, sans-serif',
      headingAr: 'Noto Kufi Arabic Bold, Helvetica Neue, Arial, sans-serif',
    },
    buttonStyles: {
      primary: 'background: linear-gradient(135deg, #D40511 0%, #B3030E 100%); border-radius: 2px; font-weight: 600; padding: 14px 32px; box-shadow: 0 2px 8px rgba(212, 5, 17, 0.3);',
      secondary: 'background: #FFCD00; border: none; border-radius: 2px; color: #000000; font-weight: 600; padding: 14px 32px;',
      outline: 'background: transparent; border: 2px solid #D40511; border-radius: 2px; color: #D40511; padding: 14px 32px;',
      link: 'background: transparent; color: #D40511; text-decoration: underline; padding: 0;',
    },
    borderRadius: {
      sm: '2px',
      md: '2px',
      lg: '4px',
      xl: '6px',
    },
    shadows: {
      sm: '0 1px 3px rgba(0, 0, 0, 0.12)',
      md: '0 2px 8px rgba(0, 0, 0, 0.15)',
      lg: '0 4px 16px rgba(0, 0, 0, 0.18)',
      xl: '0 8px 32px rgba(0, 0, 0, 0.22)',
    },
    heroImage: '/hero-dhl-DP-kKqtp.jpg',
    ogImage: '/og-dhl.jpg',
    description: 'German logistics company',
    website: 'https://www.dhl.com',
    officialColors: ['#D40511', '#FFCD00', '#000000'],
  },

  // === REGIONAL EXPRESS ===
  smsa: {
    id: 'smsa',
    name: 'SMSA Express',
    nameAr: 'سمسا إكسبريس',
    country: 'UAE',
    logo: 'https://www.smsaexpress.com/logo.png',
    colors: {
      primary: '#1E3A8A',
      primaryDark: '#1E3A8A',
      primaryLight: '#2563EB',
      secondary: '#EA580C',
      secondaryDark: '#C2410C',
      secondaryLight: '#FB923C',
      accent: '#DBEAFE',
      background: '#FFFFFF',
      surface: '#FFFFFF',
      text: '#1A1A1A',
      textLight: '#666666',
      textOnPrimary: '#FFFFFF',
      border: '#E0E0E0',
      success: '#00A86B',
      warning: '#FFA500',
      error: '#DC2626',
    },
    gradients: {
      primary: 'linear-gradient(135deg, #1E3A8A 0%, #2563EB 100%)',
      secondary: 'linear-gradient(135deg, #EA580C 0%, #C2410C 100%)',
      accent: 'linear-gradient(90deg, #DBEAFE 0%, #BFDBFE 100%)',
    },
    fonts: {
      primary: 'Inter, Roboto, Arial, sans-serif',
      primaryAr: 'Noto Kufi Arabic, Inter, Arial, sans-serif',
      heading: 'Inter Bold, Roboto, Arial, sans-serif',
      headingAr: 'Noto Kufi Arabic Bold, Inter, Arial, sans-serif',
    },
    buttonStyles: {
      primary: 'background: linear-gradient(135deg, #1E3A8A 0%, #2563EB 100%); border-radius: 8px; font-weight: 500; padding: 14px 28px; box-shadow: 0 2px 8px rgba(30, 58, 138, 0.3);',
      secondary: 'background: #EA580C; border: none; border-radius: 8px; color: #FFFFFF; font-weight: 500; padding: 14px 28px;',
      outline: 'background: transparent; border: 2px solid #1E3A8A; border-radius: 8px; color: #1E3A8A; padding: 14px 28px;',
      link: 'background: transparent; color: #1E3A8A; text-decoration: underline; padding: 0;',
    },
    borderRadius: {
      sm: '4px',
      md: '8px',
      lg: '10px',
      xl: '12px',
    },
    shadows: {
      sm: '0 1px 3px rgba(0, 0, 0, 0.12)',
      md: '0 2px 8px rgba(0, 0, 0, 0.15)',
      lg: '0 4px 16px rgba(0, 0, 0, 0.18)',
      xl: '0 8px 32px rgba(0, 0, 0, 0.22)',
    },
    heroImage: '/hero-smsa-CdXqEdzT.jpg',
    ogImage: '/og-smsa.jpg',
    description: 'Express delivery services in the UAE',
    website: 'https://www.smsaexpress.com',
    officialColors: ['#1E3A8A', '#EA580C', '#DBEAFE'],
  },

  naqel: {
    id: 'naqel',
    name: 'Naqel Express',
    nameAr: 'ناickel إكسبريس',
    country: 'Saudi Arabia',
    logo: 'https://www.naqel.com.sa/logo.png',
    colors: {
      primary: '#003D82',
      primaryDark: '#002952',
      primaryLight: '#0052CC',
      secondary: '#00A86B',
      secondaryDark: '#008A59',
      secondaryLight: '#00C07F',
      accent: '#FFC107',
      background: '#FFFFFF',
      surface: '#FFFFFF',
      text: '#1A1A1A',
      textLight: '#666666',
      textOnPrimary: '#FFFFFF',
      border: '#E0E0E0',
      success: '#00A86B',
      warning: '#FFA500',
      error: '#DC2626',
    },
    gradients: {
      primary: 'linear-gradient(135deg, #003D82 0%, #0052CC 100%)',
      secondary: 'linear-gradient(135deg, #00A86B 0%, #008A59 100%)',
      accent: 'linear-gradient(90deg, #FFC107 0%, #FFA500 100%)',
    },
    fonts: {
      primary: 'Open Sans, Arial, sans-serif',
      primaryAr: 'Noto Kufi Arabic, Open Sans, Arial, sans-serif',
      heading: 'Open Sans Bold, Arial, sans-serif',
      headingAr: 'Noto Kufi Arabic Bold, Arial, sans-serif',
    },
    buttonStyles: {
      primary: 'background: linear-gradient(135deg, #003D82 0%, #0052CC 100%); border-radius: 4px; font-weight: 600; padding: 14px 28px; box-shadow: 0 2px 8px rgba(0, 61, 130, 0.3);',
      secondary: 'background: #00A86B; border: none; border-radius: 4px; color: #FFFFFF; font-weight: 600; padding: 14px 28px;',
      outline: 'background: transparent; border: 2px solid #003D82; border-radius: 4px; color: #003D82; padding: 14px 28px;',
      link: 'background: transparent; color: #003D82; text-decoration: underline; padding: 0;',
    },
    borderRadius: {
      sm: '4px',
      md: '4px',
      lg: '6px',
      xl: '10px',
    },
    shadows: {
      sm: '0 1px 3px rgba(0, 0, 0, 0.12)',
      md: '0 2px 8px rgba(0, 0, 0, 0.15)',
      lg: '0 4px 16px rgba(0, 0, 0, 0.18)',
      xl: '0 8px 32px rgba(0, 0, 0, 0.22)',
    },
    heroImage: '/hero-naqel-BkrhVp9x.jpg',
    ogImage: '/og-naqel.jpg',
    description: 'Leading logistics company in Saudi Arabia',
    website: 'https://www.naqel.com.sa',
    officialColors: ['#003D82', '#00A86B', '#FFC107'],
  },

  // === GOVERNMENT POSTAL SERVICES ===
  saudipost: {
    id: 'saudipost',
    name: 'Saudi Post',
    nameAr: 'البريد السعودي',
    country: 'Saudi Arabia',
    logo: 'https://www.saudi-post.com/logo.png',
    colors: {
      primary: '#006C35',
      primaryDark: '#004D25',
      primaryLight: '#008A45',
      secondary: '#B8860B',
      secondaryDark: '#8B6914',
      secondaryLight: '#DAA520',
      accent: '#FFFFFF',
      background: '#FFFFFF',
      surface: '#FFFFFF',
      text: '#1A1A1A',
      textLight: '#666666',
      textOnPrimary: '#FFFFFF',
      border: '#E0E0E0',
      success: '#00A86B',
      warning: '#FFA500',
      error: '#DC2626',
    },
    gradients: {
      primary: 'linear-gradient(135deg, #006C35 0%, #004D25 100%)',
      secondary: 'linear-gradient(135deg, #B8860B 0%, #8B6914 100%)',
      accent: 'linear-gradient(90deg, #DAA520 0%, #B8860B 100%)',
    },
    fonts: {
      primary: 'Noto Sans Arabic, Arial, sans-serif',
      primaryAr: 'Noto Kufi Arabic, Arial, sans-serif',
      heading: 'Noto Sans Arabic Bold, Arial, sans-serif',
      headingAr: 'Noto Kufi Arabic Bold, Arial, sans-serif',
    },
    buttonStyles: {
      primary: 'background: linear-gradient(135deg, #006C35 0%, #004D25 100%); border-radius: 4px; font-weight: 600; padding: 14px 32px; box-shadow: 0 2px 8px rgba(0, 108, 53, 0.3);',
      secondary: 'background: #B8860B; border: none; border-radius: 4px; color: #FFFFFF; font-weight: 600; padding: 14px 32px;',
      outline: 'background: transparent; border: 2px solid #006C35; border-radius: 4px; color: #006C35; padding: 14px 32px;',
      link: 'background: transparent; color: #006C35; text-decoration: underline; padding: 0;',
    },
    borderRadius: {
      sm: '4px',
      md: '4px',
      lg: '6px',
      xl: '10px',
    },
    shadows: {
      sm: '0 1px 3px rgba(0, 0, 0, 0.12)',
      md: '0 2px 8px rgba(0, 0, 0, 0.15)',
      lg: '0 4px 16px rgba(0, 0, 0, 0.18)',
      xl: '0 8px 32px rgba(0, 0, 0, 0.22)',
    },
    heroImage: '/hero-saudipost-DnUuHyF0.jpg',
    ogImage: '/og-saudi-post.jpg',
    description: 'Official postal service of Saudi Arabia',
    website: 'https://www.saudi-post.com',
    officialColors: ['#006C35', '#B8860B', '#FFFFFF'],
  },

  emiratespost: {
    id: 'emiratespost',
    name: 'Emirates Post',
    nameAr: 'بريد الإمارات',
    country: 'UAE',
    logo: 'https://www.emiratespost.ae/logo.png',
    colors: {
      primary: '#C8102E',
      primaryDark: '#8B0000',
      primaryLight: '#E31837',
      secondary: '#D4AF37',
      secondaryDark: '#B8860B',
      secondaryLight: '#F4D03F',
      accent: '#FFFFFF',
      background: '#FFFFFF',
      surface: '#FFFFFF',
      text: '#1A1A1A',
      textLight: '#666666',
      textOnPrimary: '#FFFFFF',
      border: '#E0E0E0',
      success: '#00A86B',
      warning: '#FFA500',
      error: '#DC2626',
    },
    gradients: {
      primary: 'linear-gradient(135deg, #C8102E 0%, #8B0000 100%)',
      secondary: 'linear-gradient(135deg, #D4AF37 0%, #B8860B 100%)',
      accent: 'linear-gradient(90deg, #E31837 0%, #C8102E 100%)',
    },
    fonts: {
      primary: 'Emirates Type, Arial, sans-serif',
      primaryAr: 'Noto Kufi Arabic, Arial, sans-serif',
      heading: 'Emirates Type Bold, Arial, sans-serif',
      headingAr: 'Noto Kufi Arabic Bold, Arial, sans-serif',
    },
    buttonStyles: {
      primary: 'background: linear-gradient(135deg, #C8102E 0%, #8B0000 100%); border-radius: 6px; font-weight: 600; padding: 14px 32px; box-shadow: 0 2px 8px rgba(200, 16, 46, 0.3);',
      secondary: 'background: #D4AF37; border: none; border-radius: 6px; color: #1A1A1A; font-weight: 600; padding: 14px 32px;',
      outline: 'background: transparent; border: 2px solid #C8102E; border-radius: 6px; color: #C8102E; padding: 14px 32px;',
      link: 'background: transparent; color: #C8102E; text-decoration: underline; padding: 0;',
    },
    borderRadius: {
      sm: '4px',
      md: '6px',
      lg: '8px',
      xl: '12px',
    },
    shadows: {
      sm: '0 1px 3px rgba(0, 0, 0, 0.12)',
      md: '0 2px 8px rgba(0, 0, 0, 0.15)',
      lg: '0 4px 16px rgba(0, 0, 0, 0.18)',
      xl: '0 8px 32px rgba(0, 0, 0, 0.22)',
    },
    heroImage: '/hero-emiratespost.jpg',
    ogImage: '/og-emiratespost.jpg',
    description: 'Official postal service of the UAE',
    website: 'https://www.emiratespost.ae',
    officialColors: ['#C8102E', '#D4AF37', '#FFFFFF'],
  },

  qpost: {
    id: 'qpost',
    name: 'Qatar Post',
    nameAr: 'بريد قطر',
    country: 'Qatar',
    logo: 'https://www.qpost.com.qa/logo.png',
    colors: {
      primary: '#800020',
      primaryDark: '#4D0013',
      primaryLight: '#9B1B30',
      secondary: '#FFD700',
      secondaryDark: '#DAA520',
      secondaryLight: '#FFED4E',
      accent: '#FFFFFF',
      background: '#FFFFFF',
      surface: '#FFFFFF',
      text: '#1A1A1A',
      textLight: '#666666',
      textOnPrimary: '#FFFFFF',
      border: '#E0E0E0',
      success: '#00A86B',
      warning: '#FFA500',
      error: '#DC2626',
    },
    gradients: {
      primary: 'linear-gradient(135deg, #800020 0%, #4D0013 100%)',
      secondary: 'linear-gradient(135deg, #FFD700 0%, #DAA520 100%)',
      accent: 'linear-gradient(90deg, #9B1B30 0%, #800020 100%)',
    },
    fonts: {
      primary: 'QPost Font, Arial, sans-serif',
      primaryAr: 'Noto Kufi Arabic, Arial, sans-serif',
      heading: 'QPost Font Bold, Arial, sans-serif',
      headingAr: 'Noto Kufi Arabic Bold, Arial, sans-serif',
    },
    buttonStyles: {
      primary: 'background: linear-gradient(135deg, #800020 0%, #4D0013 100%); border-radius: 5px; font-weight: 600; padding: 14px 32px; box-shadow: 0 2px 8px rgba(128, 0, 32, 0.3);',
      secondary: 'background: #FFD700; border: none; border-radius: 5px; color: #1A1A1A; font-weight: 600; padding: 14px 32px;',
      outline: 'background: transparent; border: 2px solid #800020; border-radius: 5px; color: #800020; padding: 14px 32px;',
      link: 'background: transparent; color: #800020; text-decoration: underline; padding: 0;',
    },
    borderRadius: {
      sm: '4px',
      md: '5px',
      lg: '7px',
      xl: '10px',
    },
    shadows: {
      sm: '0 1px 3px rgba(0, 0, 0, 0.12)',
      md: '0 2px 8px rgba(0, 0, 0, 0.15)',
      lg: '0 4px 16px rgba(0, 0, 0, 0.18)',
      xl: '0 8px 32px rgba(0, 0, 0, 0.22)',
    },
    heroImage: '/hero-qpost-C-ZXEmiH.jpg',
    ogImage: '/og-qpost.jpg',
    description: 'Official postal service of Qatar',
    website: 'https://www.qpost.com.qa',
    officialColors: ['#800020', '#FFD700', '#FFFFFF'],
  },

  kwpost: {
    id: 'kwpost',
    name: 'Kuwait Post',
    nameAr: 'بريد الكويت',
    country: 'Kuwait',
    logo: 'https://www.kwpost.com.kw/logo.png',
    colors: {
      primary: '#003087',
      primaryDark: '#001F5C',
      primaryLight: '#0047AB',
      secondary: '#CC0000',
      secondaryDark: '#990000',
      secondaryLight: '#FF3333',
      accent: '#C0C0C0',
      background: '#FFFFFF',
      surface: '#FFFFFF',
      text: '#1A1A1A',
      textLight: '#666666',
      textOnPrimary: '#FFFFFF',
      border: '#E0E0E0',
      success: '#00A86B',
      warning: '#FFA500',
      error: '#DC2626',
    },
    gradients: {
      primary: 'linear-gradient(135deg, #003087 0%, #001F5C 100%)',
      secondary: 'linear-gradient(135deg, #CC0000 0%, #990000 100%)',
      accent: 'linear-gradient(90deg, #C0C0C0 0%, #A8A8A8 100%)',
    },
    fonts: {
      primary: 'Kuwait Post Font, Arial, sans-serif',
      primaryAr: 'Noto Kufi Arabic, Arial, sans-serif',
      heading: 'Kuwait Post Font Bold, Arial, sans-serif',
      headingAr: 'Noto Kufi Arabic Bold, Arial, sans-serif',
    },
    buttonStyles: {
      primary: 'background: linear-gradient(135deg, #003087 0%, #001F5C 100%); border-radius: 4px; font-weight: 600; padding: 14px 32px; box-shadow: 0 2px 8px rgba(0, 48, 135, 0.3);',
      secondary: 'background: #CC0000; border: none; border-radius: 4px; color: #FFFFFF; font-weight: 600; padding: 14px 32px;',
      outline: 'background: transparent; border: 2px solid #003087; border-radius: 4px; color: #003087; padding: 14px 32px;',
      link: 'background: transparent; color: #003087; text-decoration: underline; padding: 0;',
    },
    borderRadius: {
      sm: '4px',
      md: '4px',
      lg: '6px',
      xl: '10px',
    },
    shadows: {
      sm: '0 1px 3px rgba(0, 0, 0, 0.12)',
      md: '0 2px 8px rgba(0, 0, 0, 0.15)',
      lg: '0 4px 16px rgba(0, 0, 0, 0.18)',
      xl: '0 8px 32px rgba(0, 0, 0, 0.22)',
    },
    heroImage: '/hero-kwpost-BGHDk7Kn.jpg',
    ogImage: '/og-kwpost.jpg',
    description: 'Official postal service of Kuwait',
    website: 'https://www.kwpost.com.kw',
    officialColors: ['#003087', '#CC0000', '#C0C0C0'],
  },

  bahpost: {
    id: 'bahpost',
    name: 'Bahrain Post',
    nameAr: 'بريد البحرين',
    country: 'Bahrain',
    logo: 'https://www.bahrainpost.com.bh/logo.png',
    colors: {
      primary: '#C1272D',
      primaryDark: '#8B0000',
      primaryLight: '#DC143C',
      secondary: '#FFFFFF',
      secondaryDark: '#E0E0E0',
      secondaryLight: '#F5F5F5',
      accent: '#FFD700',
      background: '#FFFFFF',
      surface: '#FFFFFF',
      text: '#1A1A1A',
      textLight: '#666666',
      textOnPrimary: '#FFFFFF',
      border: '#E0E0E0',
      success: '#00A86B',
      warning: '#FFA500',
      error: '#DC2626',
    },
    gradients: {
      primary: 'linear-gradient(135deg, #C1272D 0%, #8B0000 100%)',
      secondary: 'linear-gradient(135deg, #FFFFFF 0%, #E0E0E0 100%)',
      accent: 'linear-gradient(90deg, #FFD700 0%, #DAA520 100%)',
    },
    fonts: {
      primary: 'Bahrain Font, Arial, sans-serif',
      primaryAr: 'Noto Kufi Arabic, Arial, sans-serif',
      heading: 'Bahrain Font Bold, Arial, sans-serif',
      headingAr: 'Noto Kufi Arabic Bold, Arial, sans-serif',
    },
    buttonStyles: {
      primary: 'background: linear-gradient(135deg, #C1272D 0%, #8B0000 100%); border-radius: 4px; font-weight: 600; padding: 14px 32px; box-shadow: 0 2px 8px rgba(193, 39, 45, 0.3);',
      secondary: 'background: #FFFFFF; border: 2px solid #C1272D; border-radius: 4px; color: #C1272D; font-weight: 600; padding: 14px 32px;',
      outline: 'background: transparent; border: 2px solid #C1272D; border-radius: 4px; color: #C1272D; padding: 14px 32px;',
      link: 'background: transparent; color: #C1272D; text-decoration: underline; padding: 0;',
    },
    borderRadius: {
      sm: '4px',
      md: '4px',
      lg: '6px',
      xl: '10px',
    },
    shadows: {
      sm: '0 1px 3px rgba(0, 0, 0, 0.12)',
      md: '0 2px 8px rgba(0, 0, 0, 0.15)',
      lg: '0 4px 16px rgba(0, 0, 0, 0.18)',
      xl: '0 8px 32px rgba(0, 0, 0, 0.22)',
    },
    heroImage: '/hero-bahpost-BqZJY1Mm.jpg',
    ogImage: '/og-bahpost.jpg',
    description: 'Official postal service of Bahrain',
    website: 'https://www.bahrainpost.com.bh',
    officialColors: ['#C1272D', '#FFFFFF', '#FFD700'],
  },

  omanpost: {
    id: 'omanpost',
    name: 'Oman Post',
    nameAr: 'بريد عمان',
    country: 'Oman',
    logo: 'https://www.omanpost.com.om/logo.png',
    colors: {
      primary: '#C8102E',
      primaryDark: '#8B0000',
      primaryLight: '#E31837',
      secondary: '#00732F',
      secondaryDark: '#005A25',
      secondaryLight: '#00A040',
      accent: '#FFFFFF',
      background: '#FFFFFF',
      surface: '#FFFFFF',
      text: '#1A1A1A',
      textLight: '#666666',
      textOnPrimary: '#FFFFFF',
      border: '#E0E0E0',
      success: '#00A86B',
      warning: '#FFA500',
      error: '#DC2626',
    },
    gradients: {
      primary: 'linear-gradient(135deg, #C8102E 0%, #8B0000 100%)',
      secondary: 'linear-gradient(135deg, #00732F 0%, #005A25 100%)',
      accent: 'linear-gradient(90deg, #E31837 0%, #C8102E 100%)',
    },
    fonts: {
      primary: 'Oman Post Font, Arial, sans-serif',
      primaryAr: 'Noto Kufi Arabic, Arial, sans-serif',
      heading: 'Oman Post Font Bold, Arial, sans-serif',
      headingAr: 'Noto Kufi Arabic Bold, Arial, sans-serif',
    },
    buttonStyles: {
      primary: 'background: linear-gradient(135deg, #C8102E 0%, #8B0000 100%); border-radius: 5px; font-weight: 600; padding: 14px 32px; box-shadow: 0 2px 8px rgba(200, 16, 46, 0.3);',
      secondary: 'background: #00732F; border: none; border-radius: 5px; color: #FFFFFF; font-weight: 600; padding: 14px 32px;',
      outline: 'background: transparent; border: 2px solid #C8102E; border-radius: 5px; color: #C8102E; padding: 14px 32px;',
      link: 'background: transparent; color: #C8102E; text-decoration: underline; padding: 0;',
    },
    borderRadius: {
      sm: '4px',
      md: '5px',
      lg: '7px',
      xl: '10px',
    },
    shadows: {
      sm: '0 1px 3px rgba(0, 0, 0, 0.12)',
      md: '0 2px 8px rgba(0, 0, 0, 0.15)',
      lg: '0 4px 16px rgba(0, 0, 0, 0.18)',
      xl: '0 8px 32px rgba(0, 0, 0, 0.22)',
    },
    heroImage: '/hero-omanpost-BbtHObOr.jpg',
    ogImage: '/og-omanpost.jpg',
    description: 'Official postal service of Oman',
    website: 'https://www.omanpost.com.om',
    officialColors: ['#C8102E', '#00732F', '#FFFFFF'],
  },

  // === LOGISTICS COMPANIES ===
  hellmann: {
    id: 'hellmann',
    name: 'Hellmann Worldwide Logistics',
    nameAr: 'هيلمان للخدمات اللوجستية',
    country: 'Germany',
    logo: 'https://www.hellmann.com/logo.png',
    colors: {
      primary: '#003D7A',
      primaryDark: '#002952',
      primaryLight: '#0052A3',
      secondary: '#FF6600',
      secondaryDark: '#E65C00',
      secondaryLight: '#FF8533',
      accent: '#4A90E2',
      background: '#FFFFFF',
      surface: '#FFFFFF',
      text: '#1A1A1A',
      textLight: '#666666',
      textOnPrimary: '#FFFFFF',
      border: '#E0E0E0',
      success: '#00A86B',
      warning: '#FFA500',
      error: '#DC2626',
    },
    gradients: {
      primary: 'linear-gradient(135deg, #003D7A 0%, #002952 100%)',
      secondary: 'linear-gradient(135deg, #FF6600 0%, #E65C00 100%)',
      accent: 'linear-gradient(90deg, #4A90E2 0%, #0052A3 100%)',
    },
    fonts: {
      primary: 'Hellmann Sans, Arial, sans-serif',
      primaryAr: 'Noto Kufi Arabic, Arial, sans-serif',
      heading: 'Hellmann Sans Bold, Arial, sans-serif',
      headingAr: 'Noto Kufi Arabic Bold, Arial, sans-serif',
    },
    buttonStyles: {
      primary: 'background: linear-gradient(135deg, #003D7A 0%, #002952 100%); border-radius: 6px; font-weight: 600; padding: 14px 32px; box-shadow: 0 2px 8px rgba(0, 61, 122, 0.3);',
      secondary: 'background: #FF6600; border: none; border-radius: 6px; color: #FFFFFF; font-weight: 600; padding: 14px 32px;',
      outline: 'background: transparent; border: 2px solid #003D7A; border-radius: 6px; color: #003D7A; padding: 14px 32px;',
      link: 'background: transparent; color: #003D7A; text-decoration: underline; padding: 0;',
    },
    borderRadius: {
      sm: '4px',
      md: '6px',
      lg: '8px',
      xl: '12px',
    },
    shadows: {
      sm: '0 1px 3px rgba(0, 0, 0, 0.12)',
      md: '0 2px 8px rgba(0, 0, 0, 0.15)',
      lg: '0 4px 16px rgba(0, 0, 0, 0.18)',
      xl: '0 8px 32px rgba(0, 0, 0, 0.22)',
    },
    heroImage: '/hero-hellmann-TfVF02fa.jpg',
    ogImage: '/og-hellmann.jpg',
    description: 'International logistics and transportation company',
    website: 'https://www.hellmann.com',
    officialColors: ['#003D7A', '#FF6600', '#4A90E2'],
  },

  zajil: {
    id: 'zajil',
    name: 'Zajil Express',
    nameAr: 'زاجل إكسبريس',
    country: 'Saudi Arabia',
    logo: 'https://www.zajil.com/logo.png',
    colors: {
      primary: '#1E40AF',
      primaryDark: '#1E3A8A',
      primaryLight: '#2563EB',
      secondary: '#FBBF24',
      secondaryDark: '#F59E0B',
      secondaryLight: '#FCD34D',
      accent: '#FFFFFF',
      background: '#FFFFFF',
      surface: '#FFFFFF',
      text: '#1A1A1A',
      textLight: '#666666',
      textOnPrimary: '#FFFFFF',
      border: '#E0E0E0',
      success: '#00A86B',
      warning: '#FFA500',
      error: '#DC2626',
    },
    gradients: {
      primary: 'linear-gradient(135deg, #1E40AF 0%, #1E3A8A 100%)',
      secondary: 'linear-gradient(135deg, #FBBF24 0%, #F59E0B 100%)',
      accent: 'linear-gradient(90deg, #2563EB 0%, #1E40AF 100%)',
    },
    fonts: {
      primary: 'Inter, Arial, sans-serif',
      primaryAr: 'Noto Kufi Arabic, Inter, Arial, sans-serif',
      heading: 'Inter Bold, Arial, sans-serif',
      headingAr: 'Noto Kufi Arabic Bold, Inter, Arial, sans-serif',
    },
    buttonStyles: {
      primary: 'background: linear-gradient(135deg, #1E40AF 0%, #1E3A8A 100%); border-radius: 8px; font-weight: 600; padding: 14px 32px; box-shadow: 0 2px 8px rgba(30, 64, 175, 0.3);',
      secondary: 'background: #FBBF24; border: none; border-radius: 8px; color: #1A1A1A; font-weight: 600; padding: 14px 32px;',
      outline: 'background: transparent; border: 2px solid #1E40AF; border-radius: 8px; color: #1E40AF; padding: 14px 32px;',
      link: 'background: transparent; color: #1E40AF; text-decoration: underline; padding: 0;',
    },
    borderRadius: {
      sm: '4px',
      md: '8px',
      lg: '10px',
      xl: '14px',
    },
    shadows: {
      sm: '0 1px 3px rgba(0, 0, 0, 0.12)',
      md: '0 2px 8px rgba(0, 0, 0, 0.15)',
      lg: '0 4px 16px rgba(0, 0, 0, 0.18)',
      xl: '0 8px 32px rgba(0, 0, 0, 0.22)',
    },
    heroImage: '/hero-zajil-B0TFDgTp.jpg',
    ogImage: '/og-zajil.jpg',
    description: 'Express delivery services in Saudi Arabia',
    website: 'https://www.zajil.com',
    officialColors: ['#1E40AF', '#FBBF24', '#FFFFFF'],
  },

  dsv: {
    id: 'dsv',
    name: 'DSV',
    nameAr: 'دي إس في',
    country: 'Denmark',
    logo: 'https://www.dsv.com/logo.png',
    colors: {
      primary: '#D50000',
      primaryDark: '#B71C1C',
      primaryLight: '#E53935',
      secondary: '#424242',
      secondaryDark: '#212121',
      secondaryLight: '#616161',
      accent: '#1976D2',
      background: '#FFFFFF',
      surface: '#FFFFFF',
      text: '#1A1A1A',
      textLight: '#666666',
      textOnPrimary: '#FFFFFF',
      border: '#E0E0E0',
      success: '#00A86B',
      warning: '#FFA500',
      error: '#DC2626',
    },
    gradients: {
      primary: 'linear-gradient(135deg, #D50000 0%, #B71C1C 100%)',
      secondary: 'linear-gradient(135deg, #424242 0%, #212121 100%)',
      accent: 'linear-gradient(90deg, #1976D2 0%, #0D47A1 100%)',
    },
    fonts: {
      primary: 'DSV Sans, Arial, sans-serif',
      primaryAr: 'Noto Kufi Arabic, Arial, sans-serif',
      heading: 'DSV Sans Bold, Arial, sans-serif',
      headingAr: 'Noto Kufi Arabic Bold, Arial, sans-serif',
    },
    buttonStyles: {
      primary: 'background: linear-gradient(135deg, #D50000 0%, #B71C1C 100%); border-radius: 4px; font-weight: 600; padding: 14px 32px; box-shadow: 0 2px 8px rgba(213, 0, 0, 0.3);',
      secondary: 'background: #424242; border: none; border-radius: 4px; color: #FFFFFF; font-weight: 600; padding: 14px 32px;',
      outline: 'background: transparent; border: 2px solid #D50000; border-radius: 4px; color: #D50000; padding: 14px 32px;',
      link: 'background: transparent; color: #D50000; text-decoration: underline; padding: 0;',
    },
    borderRadius: {
      sm: '4px',
      md: '4px',
      lg: '6px',
      xl: '10px',
    },
    shadows: {
      sm: '0 1px 3px rgba(0, 0, 0, 0.12)',
      md: '0 2px 8px rgba(0, 0, 0, 0.15)',
      lg: '0 4px 16px rgba(0, 0, 0, 0.18)',
      xl: '0 8px 32px rgba(0, 0, 0, 0.22)',
    },
    heroImage: '/hero-dsv-vM8QsdNK.jpg',
    ogImage: '/og-dsv.jpg',
    description: 'Global transport and logistics company',
    website: 'https://www.dsv.com',
    officialColors: ['#D50000', '#424242', '#1976D2'],
  },

  shipco: {
    id: 'shipco',
    name: 'Shipco Transport',
    nameAr: 'شيبكو ترانسport',
    country: 'USA',
    logo: 'https://www.shipco.com/logo.png',
    colors: {
      primary: '#0072CE',
      primaryDark: '#005BA1',
      primaryLight: '#0084D6',
      secondary: '#FF6B35',
      secondaryDark: '#E65C00',
      secondaryLight: '#FF8C61',
      accent: '#4FC3F7',
      background: '#FFFFFF',
      surface: '#FFFFFF',
      text: '#1A1A1A',
      textLight: '#666666',
      textOnPrimary: '#FFFFFF',
      border: '#E0E0E0',
      success: '#00A86B',
      warning: '#FFA500',
      error: '#DC2626',
    },
    gradients: {
      primary: 'linear-gradient(135deg, #0072CE 0%, #005BA1 100%)',
      secondary: 'linear-gradient(135deg, #FF6B35 0%, #E65C00 100%)',
      accent: 'linear-gradient(90deg, #4FC3F7 0%, #0072CE 100%)',
    },
    fonts: {
      primary: 'Source Sans Pro, Helvetica, Arial, sans-serif',
      primaryAr: 'Noto Kufi Arabic, Helvetica, Arial, sans-serif',
      heading: 'Source Sans Pro Bold, Helvetica, Arial, sans-serif',
      headingAr: 'Noto Kufi Arabic Bold, Helvetica, Arial, sans-serif',
    },
    buttonStyles: {
      primary: 'background: linear-gradient(135deg, #0072CE 0%, #005BA1 100%); border-radius: 6px; font-weight: 600; padding: 14px 32px; box-shadow: 0 2px 8px rgba(0, 114, 206, 0.3);',
      secondary: 'background: #FF6B35; border: none; border-radius: 6px; color: #FFFFFF; font-weight: 600; padding: 14px 32px;',
      outline: 'background: transparent; border: 2px solid #0072CE; border-radius: 6px; color: #0072CE; padding: 14px 32px;',
      link: 'background: transparent; color: #0072CE; text-decoration: underline; padding: 0;',
    },
    borderRadius: {
      sm: '4px',
      md: '6px',
      lg: '8px',
      xl: '12px',
    },
    shadows: {
      sm: '0 1px 3px rgba(0, 0, 0, 0.12)',
      md: '0 2px 8px rgba(0, 0, 0, 0.15)',
      lg: '0 4px 16px rgba(0, 0, 0, 0.18)',
      xl: '0 8px 32px rgba(0, 0, 0, 0.22)',
    },
    heroImage: '/hero-shipco-DoZ-YN2P.jpg',
    ogImage: '/og-shipco.jpg',
    description: 'Global logistics services provider',
    website: 'https://www.shipco.com',
    officialColors: ['#0072CE', '#FF6B35', '#4FC3F7'],
  },

  empost: {
    id: 'empost',
    name: 'Empost',
    nameAr: 'إيمبوست',
    country: 'UAE',
    logo: 'https://www.empost.ae/logo.png',
    colors: {
      primary: '#009639',
      primaryDark: '#007A30',
      primaryLight: '#00B04F',
      secondary: '#0066CC',
      secondaryDark: '#0052A3',
      secondaryLight: '#0080E6',
      accent: '#90EE90',
      background: '#FFFFFF',
      surface: '#FFFFFF',
      text: '#1A1A1A',
      textLight: '#666666',
      textOnPrimary: '#FFFFFF',
      border: '#E0E0E0',
      success: '#00A86B',
      warning: '#FFA500',
      error: '#DC2626',
    },
    gradients: {
      primary: 'linear-gradient(135deg, #009639 0%, #007A30 100%)',
      secondary: 'linear-gradient(135deg, #0066CC 0%, #0052A3 100%)',
      accent: 'linear-gradient(90deg, #90EE90 0%, #00B04F 100%)',
    },
    fonts: {
      primary: 'Open Sans, Arial, sans-serif',
      primaryAr: 'Noto Kufi Arabic, Arial, sans-serif',
      heading: 'Open Sans Bold, Arial, sans-serif',
      headingAr: 'Noto Kufi Arabic Bold, Arial, sans-serif',
    },
    buttonStyles: {
      primary: 'background: linear-gradient(135deg, #009639 0%, #007A30 100%); border-radius: 8px; font-weight: 600; padding: 14px 32px; box-shadow: 0 2px 8px rgba(0, 150, 57, 0.3);',
      secondary: 'background: #0066CC; border: none; border-radius: 8px; color: #FFFFFF; font-weight: 600; padding: 14px 32px;',
      outline: 'background: transparent; border: 2px solid #009639; border-radius: 8px; color: #009639; padding: 14px 32px;',
      link: 'background: transparent; color: #009639; text-decoration: underline; padding: 0;',
    },
    borderRadius: {
      sm: '4px',
      md: '8px',
      lg: '10px',
      xl: '14px',
    },
    shadows: {
      sm: '0 1px 3px rgba(0, 0, 0, 0.12)',
      md: '0 2px 8px rgba(0, 0, 0, 0.15)',
      lg: '0 4px 16px rgba(0, 0, 0, 0.18)',
      xl: '0 8px 32px rgba(0, 0, 0, 0.22)',
    },
    heroImage: '/hero-empost-C6ZB1vXX.jpg',
    ogImage: '/og-empost.jpg',
    description: 'Express delivery services in the Middle East',
    website: 'https://www.empost.ae',
    officialColors: ['#009639', '#0066CC', '#90EE90'],
  },

  alshaya: {
    id: 'alshaya',
    name: 'Alshaya Group',
    nameAr: 'مجموعة العثيمان',
    country: 'Kuwait',
    logo: 'https://www.alshaya.com/logo.png',
    colors: {
      primary: '#008B8B',
      primaryDark: '#006B6B',
      primaryLight: '#20B2AA',
      secondary: '#6A0DAD',
      secondaryDark: '#4B0082',
      secondaryLight: '#8A2BE2',
      accent: '#FFD700',
      background: '#FFFFFF',
      surface: '#FFFFFF',
      text: '#1A1A1A',
      textLight: '#666666',
      textOnPrimary: '#FFFFFF',
      border: '#E0E0E0',
      success: '#00A86B',
      warning: '#FFA500',
      error: '#DC2626',
    },
    gradients: {
      primary: 'linear-gradient(135deg, #008B8B 0%, #006B6B 100%)',
      secondary: 'linear-gradient(135deg, #6A0DAD 0%, #4B0082 100%)',
      accent: 'linear-gradient(90deg, #FFD700 0%, #FFA500 100%)',
    },
    fonts: {
      primary: 'Alshaya Font, Arial, sans-serif',
      primaryAr: 'Noto Kufi Arabic, Arial, sans-serif',
      heading: 'Alshaya Font Bold, Arial, sans-serif',
      headingAr: 'Noto Kufi Arabic Bold, Arial, sans-serif',
    },
    buttonStyles: {
      primary: 'background: linear-gradient(135deg, #008B8B 0%, #006B6B 100%); border-radius: 10px; font-weight: 600; padding: 14px 32px; box-shadow: 0 2px 8px rgba(0, 139, 139, 0.3);',
      secondary: 'background: #6A0DAD; border: none; border-radius: 10px; color: #FFFFFF; font-weight: 600; padding: 14px 32px;',
      outline: 'background: transparent; border: 2px solid #008B8B; border-radius: 10px; color: #008B8B; padding: 14px 32px;',
      link: 'background: transparent; color: #008B8B; text-decoration: underline; padding: 0;',
    },
    borderRadius: {
      sm: '6px',
      md: '10px',
      lg: '12px',
      xl: '16px',
    },
    shadows: {
      sm: '0 1px 3px rgba(0, 0, 0, 0.12)',
      md: '0 2px 8px rgba(0, 0, 0, 0.15)',
      lg: '0 4px 16px rgba(0, 0, 0, 0.18)',
      xl: '0 8px 32px rgba(0, 0, 0, 0.22)',
    },
    heroImage: '/hero-alshaya-BRUY7tcg.jpg',
    ogImage: '/og-alshaya.jpg',
    description: 'International retail franchise operator',
    website: 'https://www.alshaya.com',
    officialColors: ['#008B8B', '#6A0DAD', '#FFD700'],
  },

  alfuttaim: {
    id: 'alfuttaim',
    name: 'Al-Futtaim Group',
    nameAr: 'مجموعة الفطيم',
    country: 'UAE',
    logo: 'https://www.alfuttaim.com/logo.png',
    colors: {
      primary: '#003DA5',
      primaryDark: '#002952',
      primaryLight: '#0052CC',
      secondary: '#CC0000',
      secondaryDark: '#990000',
      secondaryLight: '#FF3333',
      accent: '#C0C0C0',
      background: '#FFFFFF',
      surface: '#FFFFFF',
      text: '#1A1A1A',
      textLight: '#666666',
      textOnPrimary: '#FFFFFF',
      border: '#E0E0E0',
      success: '#00A86B',
      warning: '#FFA500',
      error: '#DC2626',
    },
    gradients: {
      primary: 'linear-gradient(135deg, #003DA5 0%, #002952 100%)',
      secondary: 'linear-gradient(135deg, #CC0000 0%, #990000 100%)',
      accent: 'linear-gradient(90deg, #C0C0C0 0%, #A8A8A8 100%)',
    },
    fonts: {
      primary: 'Futtaim Sans, Arial, sans-serif',
      primaryAr: 'Noto Kufi Arabic, Arial, sans-serif',
      heading: 'Futtaim Sans Bold, Arial, sans-serif',
      headingAr: 'Noto Kufi Arabic Bold, Arial, sans-serif',
    },
    buttonStyles: {
      primary: 'background: linear-gradient(135deg, #003DA5 0%, #002952 100%); border-radius: 6px; font-weight: 600; padding: 14px 32px; box-shadow: 0 2px 8px rgba(0, 61, 165, 0.3);',
      secondary: 'background: #CC0000; border: none; border-radius: 6px; color: #FFFFFF; font-weight: 600; padding: 14px 32px;',
      outline: 'background: transparent; border: 2px solid #003DA5; border-radius: 6px; color: #003DA5; padding: 14px 32px;',
      link: 'background: transparent; color: #003DA5; text-decoration: underline; padding: 0;',
    },
    borderRadius: {
      sm: '4px',
      md: '6px',
      lg: '8px',
      xl: '12px',
    },
    shadows: {
      sm: '0 1px 3px rgba(0, 0, 0, 0.12)',
      md: '0 2px 8px rgba(0, 0, 0, 0.15)',
      lg: '0 4px 16px rgba(0, 0, 0, 0.18)',
      xl: '0 8px 32px rgba(0, 0, 0, 0.22)',
    },
    heroImage: '/hero-alfuttaim-CCbbDCNu.jpg',
    ogImage: '/og-alfuttaim.jpg',
    description: 'Diversified business group in the Middle East',
    website: 'https://www.alfuttaim.com',
    officialColors: ['#003DA5', '#CC0000', '#C0C0C0'],
  },

  albaraka: {
    id: 'albaraka',
    name: 'Al Baraka Banking',
    nameAr: 'بنك البركة',
    country: 'Bahrain',
    logo: 'https://www.albaraka.com/logo.png',
    colors: {
      primary: '#006400',
      primaryDark: '#013220',
      primaryLight: '#228B22',
      secondary: '#DAA520',
      secondaryDark: '#B8860B',
      secondaryLight: '#F4D03F',
      accent: '#FFFFFF',
      background: '#FFFFFF',
      surface: '#FFFFFF',
      text: '#1A1A1A',
      textLight: '#666666',
      textOnPrimary: '#FFFFFF',
      border: '#E0E0E0',
      success: '#00A86B',
      warning: '#FFA500',
      error: '#DC2626',
    },
    gradients: {
      primary: 'linear-gradient(135deg, #006400 0%, #013220 100%)',
      secondary: 'linear-gradient(135deg, #DAA520 0%, #B8860B 100%)',
      accent: 'linear-gradient(90deg, #228B22 0%, #006400 100%)',
    },
    fonts: {
      primary: 'Islamic Font, Arial, sans-serif',
      primaryAr: 'Noto Kufi Arabic, Arial, sans-serif',
      heading: 'Islamic Font Bold, Arial, sans-serif',
      headingAr: 'Noto Kufi Arabic Bold, Arial, sans-serif',
    },
    buttonStyles: {
      primary: 'background: linear-gradient(135deg, #006400 0%, #013220 100%); border-radius: 6px; font-weight: 600; padding: 14px 32px; box-shadow: 0 2px 8px rgba(0, 100, 0, 0.3);',
      secondary: 'background: #DAA520; border: none; border-radius: 6px; color: #1A1A1A; font-weight: 600; padding: 14px 32px;',
      outline: 'background: transparent; border: 2px solid #006400; border-radius: 6px; color: #006400; padding: 14px 32px;',
      link: 'background: transparent; color: #006400; text-decoration: underline; padding: 0;',
    },
    borderRadius: {
      sm: '4px',
      md: '6px',
      lg: '8px',
      xl: '12px',
    },
    shadows: {
      sm: '0 1px 3px rgba(0, 0, 0, 0.12)',
      md: '0 2px 8px rgba(0, 0, 0, 0.15)',
      lg: '0 4px 16px rgba(0, 0, 0, 0.18)',
      xl: '0 8px 32px rgba(0, 0, 0, 0.22)',
    },
    heroImage: '/hero-albaraka-gsV5mh9w.jpg',
    ogImage: '/og-albaraka.jpg',
    description: 'Islamic banking and financial services',
    website: 'https://www.albaraka.com',
    officialColors: ['#006400', '#DAA520', '#FFFFFF'],
  },

  genacom: {
    id: 'genacom',
    name: 'Genacom',
    nameAr: 'جنكوم',
    country: 'UAE',
    logo: 'https://www.genacom.ae/logo.png',
    colors: {
      primary: '#1565C0',
      primaryDark: '#0D47A1',
      primaryLight: '#1976D2',
      secondary: '#757575',
      secondaryDark: '#424242',
      secondaryLight: '#9E9E9E',
      accent: '#FF9800',
      background: '#FFFFFF',
      surface: '#FFFFFF',
      text: '#1A1A1A',
      textLight: '#666666',
      textOnPrimary: '#FFFFFF',
      border: '#E0E0E0',
      success: '#00A86B',
      warning: '#FFA500',
      error: '#DC2626',
    },
    gradients: {
      primary: 'linear-gradient(135deg, #1565C0 0%, #0D47A1 100%)',
      secondary: 'linear-gradient(135deg, #757575 0%, #424242 100%)',
      accent: 'linear-gradient(90deg, #FF9800 0%, #F57C00 100%)',
    },
    fonts: {
      primary: 'Roboto, Arial, sans-serif',
      primaryAr: 'Noto Kufi Arabic, Arial, sans-serif',
      heading: 'Roboto Bold, Arial, sans-serif',
      headingAr: 'Noto Kufi Arabic Bold, Arial, sans-serif',
    },
    buttonStyles: {
      primary: 'background: linear-gradient(135deg, #1565C0 0%, #0D47A1 100%); border-radius: 6px; font-weight: 600; padding: 14px 32px; box-shadow: 0 2px 8px rgba(21, 101, 192, 0.3);',
      secondary: 'background: #757575; border: none; border-radius: 6px; color: #FFFFFF; font-weight: 600; padding: 14px 32px;',
      outline: 'background: transparent; border: 2px solid #1565C0; border-radius: 6px; color: #1565C0; padding: 14px 32px;',
      link: 'background: transparent; color: #1565C0; text-decoration: underline; padding: 0;',
    },
    borderRadius: {
      sm: '4px',
      md: '6px',
      lg: '8px',
      xl: '12px',
    },
    shadows: {
      sm: '0 1px 3px rgba(0, 0, 0, 0.12)',
      md: '0 2px 8px rgba(0, 0, 0, 0.15)',
      lg: '0 4px 16px rgba(0, 0, 0, 0.18)',
      xl: '0 8px 32px rgba(0, 0, 0, 0.22)',
    },
    heroImage: '/hero-genacom-ByjBrhP-.jpg',
    ogImage: '/og-genacom.jpg',
    description: 'Technology and telecommunications company',
    website: 'https://www.genacom.ae',
    officialColors: ['#1565C0', '#757575', '#FF9800'],
  },

  bahri: {
    id: 'bahri',
    name: 'Bahri',
    nameAr: 'بحري',
    country: 'Saudi Arabia',
    logo: 'https://www.bahri.com.sa/logo.png',
    colors: {
      primary: '#003876',
      primaryDark: '#002952',
      primaryLight: '#0052A3',
      secondary: '#0066CC',
      secondaryDark: '#0052A3',
      secondaryLight: '#3399FF',
      accent: '#C0C0C0',
      background: '#FFFFFF',
      surface: '#FFFFFF',
      text: '#1A1A1A',
      textLight: '#666666',
      textOnPrimary: '#FFFFFF',
      border: '#E0E0E0',
      success: '#00A86B',
      warning: '#FFA500',
      error: '#DC2626',
    },
    gradients: {
      primary: 'linear-gradient(135deg, #003876 0%, #002952 100%)',
      secondary: 'linear-gradient(135deg, #0066CC 0%, #0052A3 100%)',
      accent: 'linear-gradient(90deg, #C0C0C0 0%, #A8A8A8 100%)',
    },
    fonts: {
      primary: 'Bahri Sans, Arial, sans-serif',
      primaryAr: 'Noto Kufi Arabic, Arial, sans-serif',
      heading: 'Bahri Sans Bold, Arial, sans-serif',
      headingAr: 'Noto Kufi Arabic Bold, Arial, sans-serif',
    },
    buttonStyles: {
      primary: 'background: linear-gradient(135deg, #003876 0%, #002952 100%); border-radius: 6px; font-weight: 600; padding: 14px 32px; box-shadow: 0 2px 8px rgba(0, 56, 118, 0.3);',
      secondary: 'background: #0066CC; border: none; border-radius: 6px; color: #FFFFFF; font-weight: 600; padding: 14px 32px;',
      outline: 'background: transparent; border: 2px solid #003876; border-radius: 6px; color: #003876; padding: 14px 32px;',
      link: 'background: transparent; color: #003876; text-decoration: underline; padding: 0;',
    },
    borderRadius: {
      sm: '4px',
      md: '6px',
      lg: '8px',
      xl: '12px',
    },
    shadows: {
      sm: '0 1px 3px rgba(0, 0, 0, 0.12)',
      md: '0 2px 8px rgba(0, 0, 0, 0.15)',
      lg: '0 4px 16px rgba(0, 0, 0, 0.18)',
      xl: '0 8px 32px rgba(0, 0, 0, 0.22)',
    },
    heroImage: '/hero-bahri-CgdFW9Mw.jpg',
    ogImage: '/og-bahri.jpg',
    description: 'National shipping company of Saudi Arabia',
    website: 'https://www.bahri.com.sa',
    officialColors: ['#003876', '#0066CC', '#C0C0C0'],
  },
};

export const getCompanyBranding = (companyId: string): CompanyBranding => {
  return COMPANY_BRANDINGS[companyId] || COMPANY_BRANDINGS.aramex;
};

export const getAllCompanies = (): CompanyBranding[] => {
  return Object.values(COMPANY_BRANDINGS);
};

export const getCompaniesByCountry = (countryCode: string): CompanyBranding[] => {
  return getAllCompanies().filter(company => company.country === countryCode);
};
